# RAG - Assignment :

In [220]:
!pip install pypdf sentence-transformers google-genai

Requirement already satisfied: pypdf in /usr/local/lib/python3.13/dist-packages (6.19.0)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.13/dist-packages (5.7.0)
Requirement already satisfied: google-genai in /usr/local/lib/python3.13/dist-packages (2.12.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (5.16.1)
Requirement already satisfied: tokenizers>=0.19 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (0.23.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.29.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (2.11.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (2.1.3)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /usr/local/lib/python3.13/dist-packages (from google-genai) (4.14.2)
Requirement already satisfied: google-auth<2.56.0,>=2.48.1 in /usr/local/lib/python3.13/dist-packages (from google-auth[requests]<2.56.0,>=2.48.1->google-genai) (2.49.0)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in /usr/local/lib/python3.13/dist-packages (from google-genai) (0.28.1)
Requirement already satisfied: pydantic<3.0.0,>=2.12.5 in /usr/local/lib/python3.13/dist-packages (from google-genai) (2.13.5)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /usr/local/lib/python3.13/dist-packages (from google-genai) (2.34.2)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /usr/local/lib/python3.13/dist-packages (from google-genai) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in /usr/local/lib/python3.13/dist-packages (from google-genai) (15.0.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from google-genai) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.13/dist-packages (from google-genai) (1.3.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio<5.0.0,>=4.8.0->google-genai) (3.19)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.13/dist-packages (from google-auth<2.56.0,>=2.48.1->google-auth[requests]<2.56.0,>=2.48.1->google-genai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /usr/local/lib/python3.13/dist-packages (from google-auth<2.56.0,>=2.48.1->google-auth[requests]<2.56.0,>=2.48.1->google-genai) (50.0.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.13/dist-packages (from google-auth<2.56.0,>=2.48.1->google-auth[requests]<2.56.0,>=2.48.1->google-genai) (4.9.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.32.5)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.6.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.8.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.27.2)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography>=38.0.3->google-auth<2.56.0,>=2.48.1->google-auth[requests]<2.56.0,>=2.48.1->google-genai) (2.1.1)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn>=0.22.0->sentence-transformers) (3.1.2)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.13/dist-packages (from pyasn1-modules>=0.2.1->google-auth<2.56.0,>=2.48.1->google-auth[requests]<2.56.0,>=2.48.1->google-genai) (0.6.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.5)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<2.56.0,>=2.48.1->google-auth[requests]<2.56.0,>=2.48.1->google-genai) (3.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)

In [221]:
# from kaggle_secrets import UserSecretsClient

# GEMINI_API_KEY = UserSecretsClient().get_secret("GEMINI_API_KEY")

from kaggle_secrets import UserSecretsClient

GEMINI_API_KEY = UserSecretsClient().get_secret(
    "gemini_api_key"  # Use the exact name shown in Kaggle Secrets
)

assert GEMINI_API_KEY, "Gemini API key was not loaded."
print("Gemini API key loaded successfully.")

Gemini API key loaded successfully.

## 1. PDF / Dataset :

In [222]:
from pathlib import Path
from pypdf import PdfReader

PDF_PATH = Path("/kaggle/input/datasets/ksaiveekshith3306/lma-rag-assignment-data/Null_Signal_Games_Netrunner_Comprehensive_Rules_v26.03.pdf")

# basically verifying the path of the pdf
if not PDF_PATH.exists():
    raise FileNotFoundError(f"PDF not found: {PDF_PATH}")


reader = PdfReader(str(PDF_PATH))

print("Number of pages:", len(reader.pages))

Number of pages: 99

In [223]:
pages_text = []

for page_num, page in enumerate(reader.pages, start=1):
    text = page.extract_text() or ""
    pages_text.append(text)

    if page_num % 100 == 0:
        print(f"Processed {page_num} pages")

print("Total pages:", len(pages_text))
print("Pages with extracted text:", sum(bool(t.strip()) for t in pages_text))
print("Total characters:", sum(len(t) for t in pages_text))

Total pages: 99
Pages with extracted text: 99
Total characters: 370419

In [224]:
# Preview text from the first three pages
for i in range(min(3, len(pages_text))):
    print(f"\n{'=' * 20} PAGE {i + 1} {'=' * 20}\n")
    print(pages_text[i][:1500])

==================== PAGE 1 ====================

Netrunner Comprehensive Rules
Null Signal Games
This rules document is to be used as reference material. It is not intended to be read straight through. If you
still have questions after consulting this document, please ask us online via email.
This version of the Comprehensive Rules document is effective 02 March 2026 .
Summary of Changes
To see this document with a complete list of changes and with new material highlighted, please visit the
Comprehensive Rules Hub at 〈nullsignal.games/comp-rules〉.
• Added rule 1.5.2b to support Méliès U’s ability.
• Clarify link between rules 1.8.4b and 8.1.4 referencing facedown installed Runner cards.
• Added rule 1.13.3 and rule 1.13.12 to clarify properties of hosted objects.
• Added rule 1.21.3a to clarify that revealing does not turn cards faceup.
• Updated the list of subtypes (section 2.16.7) to remove illicit and add liability.
• Added section 2.18 to describe the server indicators on the back of Méliès U.
• Updated rule 3.6.5e to address all effects that could move a region upgrade between servers, not just
swap effects.
• Updated rules about the locations of counters in the play area in section 4.6.5.
• Added rule 6.1.3f to define what it means for the Runner to pass a piece of ice “after fully breaking it”.
• Expanded rules about how “end the run” effects interact with other timing structures, particularly for
cases where there is not actually a run in progress to end. Consolidated rules 6.5.9b, 7.1.8 and 7.3.7 to
cover all of t

==================== PAGE 2 ====================

Table of Contents
Summary of Changes . . . . . . . . . . . . . . 1
Table of Contents . . . . . . . . . . . . . . . . 2
1 Game Concepts . . . . . . . . . . . . . . . 4
1.1 General . . . . . . . . . . . . . . . . . 4
1.2 Golden Rules . . . . . . . . . . . . . . 4
1.3 Symbols . . . . . . . . . . . . . . . . . 4
1.4 Deck Construction . . . . . . . . . . 5
1.5 Extra Cards . . . . . . . . . . . . . . . 5
1.6 Starting the Game . . . . . . . . . . 6
1.7 Ending the Game . . . . . . . . . . . 7
1.8 Cards . . . . . . . . . . . . . . . . . . 7
1.9 Counters and Tokens . . . . . . . . . 8
1.10 Credits . . . . . . . . . . . . . . . . . 9
1.10.5 Recurring Credits . . . . . 9
1.11 Clicks . . . . . . . . . . . . . . . . . . 10
1.12 Objects . . . . . . . . . . . . . . . . 10
1.13 Host, Hosted, and Hosting . . . . . 11
1.14 Ownership and Control . . . . . . . 13
1.15 Targets . . . . . . . . . . . . . . . . . 14
1.16 Costs . . . . . . . . . . . . . . . . . . 15
1.17 Score, Scoring and Stealing . . . . 18
1.18 Advancing Cards . . . . . . . . . . . 19
1.19 Trashing . . . . . . . . . . . . . . . . 19
1.20 Memory . . . . . . . . . . . . . . . . 20
1.21 Card Visibility . . . . . . . . . . . . . 20
2 Parts of a Card . . . . . . . . . . . . . . . . 21
2.1 Name . . . . . . . . . . . . . . . . . . 21
2.2 Unique Symbol . . . . . . . . . . . . 21
2.3 Play Cost, Install Cost, or Rez Cost 21
2.4 Advancement Requirement . . . . . 21
2.5 Agenda Points . . . . . . . . . . . . . 22
2.6 Trash Cost . . . . . . . .

==================== PAGE 3 ====================

8.6.7 Steps of Playing an Event
or Operation . . . . . . . . . . 60
8.7 Searching for Cards . . . . . . . . . 60
8.8 Swapping Cards . . . . . . . . . . . 61
9 Abilities . . . . . . . . . . . . . . . . . . . . 62
9.1 General . . . . . . . . . . . . . . . . . 62
9.2 Timing and Priority . . . . . . . . . . 65
9.3 Interpreting Card Text . . . . . . . . 67
9.4 Static Abilities . . . . . . . . . . . . 69
9.5 Paid Abilities . . . . . . . . . . . . . 69
9.5.7 Steps of Using a Paid Ability 71
9.6 Conditional Abilities . . . . . . . . . 71
9.6.15 Steps of Triggering and
Resolving a Conditional Ability 75
9.7 Play Abilities . . . . . . . . . . . . . . 75
9.7.2 Steps of Resolving a Play
Ability . . . . . . . . . . . . . . 75
9.8 Subroutines . . . . . . . . . . . . . . 75
9.8.10 Steps of Resolving a
Subroutine . . . . . . . . . . . 78
9.9 Interrupts and Replacement Effects 78
9.10 Lingering Effects . . . . . . . . . . 82
9.11 Identifying Instructions . . . . . . . 83
9.12 Other Rules and Terminology . . . 84
9.12.1 Simultaneous Effects . . . 84
9.12.2 Quantities and Sets . . . . 85
9.12.3 Must . . . . . . . . . . . . . 86
9.12.4 Repeat this process . . . . 87
9.12.5 Persistent . . . . . . . . . . 87
9.12.6 Modal Abilities . . . . . . . 87
10 Additional Rules . . . . . . . . . . . . . . 88
10.1 General . . . . . . . . . . . . . . . . 88
10.1.6 Infinite Loops . . . . . . . . 88
10.2 Information . . . . . . . . . . . . . . 88
10.2.2 Hidden Information . . . . 89
10.2.3 Open Information . . .

## Chunking (rule-aware)

The rules PDF is structured around numbered rules, sub-rules, and examples. Fixed character slicing can split a rule or separate it from its exception/example. The chunker below prefers rule/paragraph boundaries, keeps page provenance, and uses a target size with a hard maximum. Both retrieval pipelines use this exact same corpus.

In [225]:
import re

# Tune these after inspecting the chunk previews.
TARGET_CHUNK_CHARS = 1400
MAX_CHUNK_CHARS = 1800
MIN_CHUNK_CHARS = 250

# A rule heading such as "6.5.7. Fully Break" or "9.8.7."
RULE_START_RE = re.compile(
    r"(?m)^\s*\d+(?:\.\d+){1,3}[a-z]?(?:\.)?\s+"
)

def split_page_into_units(page_text, page_num):
    """Split extracted PDF text into rule/paragraph-sized units."""
    text = re.sub(r"[ \t]+", " ", page_text or "").strip()
    if not text:
        return []

    # Prefer numbered rule boundaries. If a page has no rule headings,
    # fall back to blank-line paragraph boundaries.
    starts = [m.start() for m in RULE_START_RE.finditer(text)]
    if len(starts) >= 2:
        boundaries = sorted(set([0] + starts + [len(text)]))
        pieces = [
            text[boundaries[i]:boundaries[i + 1]].strip()
            for i in range(len(boundaries) - 1)
        ]
    else:
        pieces = [p.strip() for p in re.split(r"\n\s*\n", text) if p.strip()]

    return [
        {"text": piece, "pages": [page_num]}
        for piece in pieces if piece
    ]

def split_oversized_unit(unit, max_chars=MAX_CHUNK_CHARS):
    """Split a very long rule at paragraph/sentence/space boundaries."""
    text = unit["text"]
    if len(text) <= max_chars:
        return [unit]

    parts = []
    remaining = text
    while len(remaining) > max_chars:
        cut = remaining.rfind("\n", 0, max_chars)
        if cut < max_chars * 0.5:
            cut = remaining.rfind(". ", 0, max_chars)
        if cut < max_chars * 0.5:
            cut = remaining.rfind(" ", 0, max_chars)
        if cut < max_chars * 0.5:
            cut = max_chars

        piece = remaining[:cut].strip()
        if piece:
            parts.append({"text": piece, "pages": unit["pages"][:]})
        remaining = remaining[cut:].strip()

    if remaining:
        parts.append({"text": remaining, "pages": unit["pages"][:]})
    return parts

# Keep the original page text as the source of truth and preserve page metadata.
units = []
for page_num, page_text in enumerate(pages_text, start=1):
    units.extend(split_page_into_units(page_text, page_num))

# Avoid oversized chunks, then pack adjacent units to a target size.
bounded_units = []
for unit in units:
    bounded_units.extend(split_oversized_unit(unit))

chunks = []
current_texts = []
current_pages = []
current_len = 0

def flush_chunk():
    global current_texts, current_pages, current_len
    if current_texts:
        text = "\n\n".join(current_texts).strip()
        if text:
            chunks.append({
                "text": text,
                "page": min(current_pages),
                "pages": sorted(set(current_pages)),
                "start_char": None,
                "end_char": None
            })
    current_texts = []
    current_pages = []
    current_len = 0

for unit in bounded_units:
    unit_text = unit["text"]
    extra_len = len(unit_text) + (2 if current_texts else 0)

    if current_texts and current_len + extra_len > TARGET_CHUNK_CHARS:
        flush_chunk()

    # A single unit may be larger than target but has already been capped.
    current_texts.append(unit_text)
    current_pages.extend(unit["pages"])
    current_len += extra_len

flush_chunk()

# Small final chunks are merged into the previous chunk when that remains safe.
if len(chunks) > 1 and len(chunks[-1]["text"]) < MIN_CHUNK_CHARS:
    last = chunks[-1]
    previous = chunks[-2]
    if len(previous["text"]) + 2 + len(last["text"]) <= MAX_CHUNK_CHARS:
        previous["text"] += "\n\n" + last["text"]
        previous["pages"] = sorted(set(previous["pages"] + last["pages"]))
        previous["page"] = min(previous["pages"])
        chunks.pop()

print("Pages with text:", sum(bool(t.strip()) for t in pages_text))
print("Total chunks:", len(chunks))
print("Average chunk characters:", round(sum(len(c["text"]) for c in chunks) / max(len(chunks), 1)))
print("Min / max chunk characters:", min(map(lambda c: len(c["text"]), chunks)), "/", max(map(lambda c: len(c["text"]), chunks)))
print("First chunk pages:", chunks[0]["pages"] if chunks else [])
print((chunks[0]["text"][:1200] if chunks else "No chunks generated."))

Pages with text: 99
Total chunks: 315
Average chunk characters: 1177
Min / max chunk characters: 106 / 1800
First chunk pages: [1]
Netrunner Comprehensive Rules
Null Signal Games
This rules document is to be used as reference material. It is not intended to be read straight through. If you
still have questions after consulting this document, please ask us online via email.
This version of the Comprehensive Rules document is effective 02 March 2026 .
Summary of Changes
To see this document with a complete list of changes and with new material highlighted, please visit the
Comprehensive Rules Hub at 〈nullsignal.games/comp-rules〉.
• Added rule 1.5.2b to support Méliès U’s ability.
• Clarify link between rules 1.8.4b and 8.1.4 referencing facedown installed Runner cards.
• Added rule 1.13.3 and rule 1.13.12 to clarify properties of hosted objects.
• Added rule 1.21.3a to clarify that revealing does not turn cards faceup.
• Updated the list of subtypes (section 2.16.7) to remove illicit and add liability.
• Added section 2.18 to describe the server indicators on the back of Méliès U.
• Updated rule 3.6.5e to address all effects that could move a region upgrade between servers, not just
swap effects.
• Updated rules about the locations of counters in the play area in section 4.6.5.
• Added rule 6.1.3f to define what

In [226]:
for i, chunk in enumerate(chunks[:3]):
    print(f"\n--- Chunk {i + 1} ---")
    print("Page:", chunk["page"])
    print("Characters:", len(chunk["text"]))
    print(chunk["text"][:300])

--- Chunk 1 ---
Page: 1
Characters: 1758
Netrunner Comprehensive Rules
Null Signal Games
This rules document is to be used as reference material. It is not intended to be read straight through. If you
still have questions after consulting this document, please ask us online via email.
This version of the Comprehensive Rules document is eff

--- Chunk 2 ---
Page: 1
Characters: 1326
• Clarified rules about prohibitions on accesses in section 7.4.2 and rule 7.4.6a.
• Expanded section 8.3.3 to add a rule ensuring that cards about to be arranged in any order don’t need
to have their order maintained for other effects in the same instruction.
• Updated rule 8.5.12 to account for “C

--- Chunk 3 ---
Page: 2
Characters: 1360
Table of Contents
Summary of Changes . . . . . . . . . . . . . . 1
Table of Contents . . . . . . . . . . . . . . . . 2
1 Game Concepts . . . . . . . . . . . . . . . 4

1.1 General . . . . . . . . . . . . . . . . . 4

1.2 Golden Rules . . . . . . . . . . . . . . 4

1.3 Symbols . . . . . . . . . . . .

In [227]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

chunk_texts = [chunk["text"] for chunk in chunks]

embeddings = model.encode(
    chunk_texts,
    convert_to_numpy=True,
    show_progress_bar=True
)

print("Number of chunks:", len(chunk_texts))
print("Embeddings shape:", embeddings.shape)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/10 [00:00<?, ?it/s]

Number of chunks: 315
Embeddings shape: (315, 384)

In [228]:
import numpy as np
from sentence_transformers import util

query = "What happens to subroutines gained during an encounter with ice?"

query_embedding = model.encode(
    query,
    convert_to_numpy=True
)

similarities = util.cos_sim(
    query_embedding,
    embeddings
)[0].cpu().numpy()

top_k = 3
top_indices = np.argsort(similarities)[::-1][:top_k]

for rank, idx in enumerate(top_indices, start=1):
    print(f"\n--- Result {rank} ---")
    print("Page:", chunks[idx]["page"])
    print("Similarity:", round(float(similarities[idx]), 4))
    print(chunks[idx]["text"][:700])

--- Result 1 ---
Page: 76
Similarity: 0.7272
subroutines are added after other subroutines or does not specify an order. Subroutines in
this category on a single piece of ice are always identical. If the number of such subroutines
increases, the new copies are added after any previously-existing subroutines in this category.
If the number of such subroutines decreases, subroutines are lost beginning with the last
subroutine the ice previously had from the same ability and working backwards.
Example: The Corp has 3 cards in HQ while the Runner is encountering Ashigaru. After the
Runner breaks Ashigaru’s 3 subroutines, the Corp uses Panic Button to draw another card. The
new subroutine is added after the previous 3, so the Runner can use

--- Result 2 ---
Page: 46
Similarity: 0.6936
6.9.3c never occurring, meaning that subroutines on the encountered ice are neither broken
nor resolved.
c. A few bypass effects can be triggered later. If ice is bypassed in step 6.9.3b, subroutines
may or may not have been broken, but step 6.9.3c never occurs so no subroutines resolve.
Note that for ice with zero subroutines, the Runner has “broken all subroutines” if and only if
step 6.9.3b was reached. See rule 9.12.2d.
Example: The Runner plays Forked and encounters a Troll that they can bypass with Femme
Fatale. The Runner pays 0credit
to bypass the Troll with Femme Fatale. Forked does not meet its
trigger condition, and Troll is not trashed, because the opportunity to break subroutine

--- Result 3 ---
Page: 77
Similarity: 0.6899
9.8.4. For each encounter, the subroutines on the encountered ice have a status ofBROKEN or UNBROKEN
with respect to that encounter.
a. When an encounter begins, each of the encountered ice’s subroutines becomes unbroken
with respect to that encounter.
b. When a piece of ice gains 1 or more new subroutines during an encounter with it, those
subroutines come into existence unbroken with respect to that encounter.
c. When an encounter ends, card abilities can still check whether subroutines were broken or
unbroken during that encounter.

9.8.5. To BREAK a subroutine is to change its status with respect to the active encounter from unbroken to
broken. Many cards that can allow a player to break

## Baseline:

In [229]:
import numpy as np
from sentence_transformers import util

def baseline_retrieve(query, top_k=10):
    query_embedding = model.encode(
        query,
        convert_to_numpy=True
    )

    scores = util.cos_sim(
        query_embedding,
        embeddings
    )[0].cpu().numpy()

    indices = np.argsort(scores)[::-1][:top_k]

    return [
        {
            "chunk_id": int(idx),
            "page": chunks[idx]["page"],
            "pages": chunks[idx].get("pages", [chunks[idx]["page"]]),
            "text": chunks[idx]["text"],
            "score": float(scores[idx])
        }
        for idx in indices
    ]


query = "What happens to subroutines gained during an encounter with ice?"

candidates = baseline_retrieve(query, top_k=10)

print("Top 10 retrieved candidates:\n")

for rank, result in enumerate(candidates, start=1):
    print(
        f"Rank {rank} | "
        f"Chunk {result['chunk_id']} | "
        f"Page {result['page']} | "
        f"Score {result['score']:.4f}"
    )

print("\n--- Baseline Top 3 Context ---")

baseline_top3 = candidates[:3]

for result in baseline_top3:
    print(f"\nPage {result['page']}\n{result['text']}")

Top 10 retrieved candidates:

Rank 1 | Chunk 244 | Page 76 | Score 0.7272
Rank 2 | Chunk 139 | Page 46 | Score 0.6936
Rank 3 | Chunk 246 | Page 77 | Score 0.6899
Rank 4 | Chunk 138 | Page 45 | Score 0.6846
Rank 5 | Chunk 149 | Page 49 | Score 0.6581
Rank 6 | Chunk 240 | Page 75 | Score 0.6385
Rank 7 | Chunk 312 | Page 97 | Score 0.6217
Rank 8 | Chunk 137 | Page 45 | Score 0.6053
Rank 9 | Chunk 241 | Page 76 | Score 0.5887
Rank 10 | Chunk 242 | Page 76 | Score 0.5845

--- Baseline Top 3 Context ---

Page 76
subroutines are added after other subroutines or does not specify an order. Subroutines in
this category on a single piece of ice are always identical. If the number of such subroutines
increases, the new copies are added after any previously-existing subroutines in this category.
If the number of such subroutines decreases, subroutines are lost beginning with the last
subroutine the ice previously had from the same ability and working backwards.
Example: The Corp has 3 cards in HQ while the Runner is encountering Ashigaru. After the
Runner breaks Ashigaru’s 3 subroutines, the Corp uses Panic Button to draw another card. The
new subroutine is added after the previous 3, so the Runner can use Gbahali to break it.
76

Page 46
6.9.3c never occurring, meaning that subroutines on the encountered ice are neither broken
nor resolved.
c. A few bypass effects can be triggered later. If ice is bypassed in step 6.9.3b, subroutines
may or may not have been broken, but step 6.9.3c never occurs so no subroutines resolve.
Note that for ice with zero subroutines, the Runner has “broken all subroutines” if and only if
step 6.9.3b was reached. See rule 9.12.2d.
Example: The Runner plays Forked and encounters a Troll that they can bypass with Femme
Fatale. The Runner pays 0credit
to bypass the Troll with Femme Fatale. Forked does not meet its
trigger condition, and Troll is not trashed, because the opportunity to break subroutines was
never reached.

Page 77
9.8.4. For each encounter, the subroutines on the encountered ice have a status ofBROKEN or UNBROKEN
with respect to that encounter.
a. When an encounter begins, each of the encountered ice’s subroutines becomes unbroken
with respect to that encounter.
b. When a piece of ice gains 1 or more new subroutines during an encounter with it, those
subroutines come into existence unbroken with respect to that encounter.
c. When an encounter ends, card abilities can still check whether subroutines were broken or
unbroken during that encounter.

9.8.5. To BREAK a subroutine is to change its status with respect to the active encounter from unbroken to
broken. Many cards that can allow a player to break subroutines are icebreakers (seesection 3.9.5).
If the Runner breaks all the subroutines on the encountered ice, they fully break that ice (see
section 6.5.7).

## Advanced using Re-ranking:

In [230]:
from sentence_transformers import CrossEncoder

reranker = CrossEncoder(
    "cross-encoder/ms-marco-MiniLM-L-6-v2"
)

def rerank_candidates(query, candidates, top_k=3):
    pairs = [
        (query, candidate["text"])
        for candidate in candidates
    ]

    scores = reranker.predict(pairs)

    reranked = []

    for candidate, score in zip(candidates, scores):
        item = candidate.copy()
        item["rerank_score"] = float(score)
        reranked.append(item)

    reranked.sort(
        key=lambda item: item["rerank_score"],
        reverse=True
    )

    return reranked[:top_k]


reranked_top3 = rerank_candidates(
    query,
    candidates,
    top_k=3
)

print("Cross-Encoder Top 3:\n")

for rank, result in enumerate(reranked_top3, start=1):
    print(
        f"Rank {rank} | "
        f"Chunk {result['chunk_id']} | "
        f"Page {result['page']} | "
        f"Score {result['rerank_score']:.4f}"
    )

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

Cross-Encoder Top 3:

Rank 1 | Chunk 246 | Page 77 | Score 7.3383
Rank 2 | Chunk 138 | Page 45 | Score 5.7131
Rank 3 | Chunk 149 | Page 49 | Score 5.3986

In [231]:
# import pandas as pd

# baseline_ids = [c["chunk_id"] for c in candidates]
# reranked_ids = [c["chunk_id"] for c in reranked_top3]

# comparison = pd.DataFrame({
#     "Chunk ID": baseline_ids,
#     "Page": [c["page"] for c in candidates],
#     "Baseline Rank": range(1, len(candidates) + 1),
#     "Cosine Score": [c["score"] for c in candidates],
#     "Cross-Encoder Rank": [
#         next(
#             (rank for rank, item in enumerate(
#                 sorted(
#                     [
#                         {
#                             **c,
#                             "rerank_score": float(s)
#                         }
#                         for c, s in zip(
#                             candidates,
#                             reranker.predict([
#                                 (query, c["text"]) for c in candidates
#                             ])
#                         )
#                     ],
#                     key=lambda x: x["rerank_score"],
#                     reverse=True
#                 ),
#                 start=1
#             ) if item["chunk_id"] == c["chunk_id"]),
#             None
#         )
#         for c in candidates
#     ]
# })

# print(comparison.to_string(index=False))

import pandas as pd

cross_scores = reranker.predict([
    (query, candidate["text"])
    for candidate in candidates
])

reranked_all = sorted(
    [
        {**candidate, "rerank_score": float(score)}
        for candidate, score in zip(candidates, cross_scores)
    ],
    key=lambda item: item["rerank_score"],
    reverse=True
)

cross_rank = {
    item["chunk_id"]: rank
    for rank, item in enumerate(reranked_all, start=1)
}

comparison = pd.DataFrame([
    {
        "Chunk ID": item["chunk_id"],
        "PDF Page": item["page"],
        "Baseline Rank": rank,
        "Cross-Encoder Rank": cross_rank[item["chunk_id"]],
        "Baseline Score": round(item["score"], 4),
        "Cross-Encoder Score": round(
            next(
                x["rerank_score"]
                for x in reranked_all
                if x["chunk_id"] == item["chunk_id"]
            ), 4
        )
    }
    for rank, item in enumerate(candidates, start=1)
])

print(comparison.to_string(index=False))

# Keep the Top 3 from the complete reranked list
reranked_top3 = reranked_all[:3]

 Chunk ID  PDF Page  Baseline Rank  Cross-Encoder Rank  Baseline Score  Cross-Encoder Score
      244        76              1                   7          0.7272               4.3738
      139        46              2                   5          0.6936               4.8798
      246        77              3                   1          0.6899               7.3383
      138        45              4                   2          0.6846               5.7131
      149        49              5                   3          0.6581               5.3986
      240        75              6                   9          0.6385              -1.1277
      312        97              7                  10          0.6217              -5.0897
      137        45              8                   4          0.6053               5.1560
      241        76              9                   8          0.5887               3.3387
      242        76             10                   6          0.5845               4.7895

In [232]:
LLM_BACKEND = "gemini"
GEMINI_MODEL = "gemini-3.5-flash-lite"

In [233]:
from google import genai

client = genai.Client(api_key=GEMINI_API_KEY)

response = client.models.generate_content(
    model=GEMINI_MODEL,
    contents="Reply with exactly: Gemini connection successful."
)

print(response.text)

Gemini connection successful.

In [234]:
def generate_answer(prompt):
    response = client.models.generate_content(
        model=GEMINI_MODEL,
        contents=prompt
    )
    return response.text


def build_prompt(query, retrieved_chunks):
    context = "\n\n".join(
        f"[Chunk {item['chunk_id']} | PDF page {item['page']}]\n"
        f"{item['text']}"
        for item in retrieved_chunks
    )

    return f"""Answer the question using only the supplied context.

If the context does not contain enough information, state that
the answer cannot be determined from the provided context.
Do not invent rules or facts.

Question:
{query}

Context:
{context}

Answer:"""

In [235]:
import time
import pandas as pd

query = "What happens to subroutines gained during an encounter with ice?"

# Measure complete pipeline latency consistently, including LLM generation.
start = time.perf_counter()
baseline_candidates = baseline_retrieve(query, top_k=10)
baseline_retrieval_time = time.perf_counter() - start
baseline_top3 = baseline_candidates[:3]
baseline_prompt = build_prompt(query, baseline_top3)

start = time.perf_counter()
answer1 = generate_answer(baseline_prompt)
baseline_llm_time = time.perf_counter() - start
baseline_total_time = baseline_retrieval_time + baseline_llm_time

start = time.perf_counter()
advanced_candidates = baseline_retrieve(query, top_k=10)
advanced_retrieval_time = time.perf_counter() - start

start = time.perf_counter()
advanced_reranked = rerank_candidates(query, advanced_candidates, top_k=3)
advanced_reranking_time = time.perf_counter() - start
reranked_top3 = advanced_reranked
reranked_prompt = build_prompt(query, reranked_top3)

start = time.perf_counter()
answer2 = generate_answer(reranked_prompt)
reranked_llm_time = time.perf_counter() - start
reranked_total_time = advanced_retrieval_time + advanced_reranking_time + reranked_llm_time

print("===== ANSWER 1: BASELINE TOP 3 =====\n")
print(answer1)
print("\n===== ANSWER 2: CROSS-ENCODER RERANKED TOP 3 =====\n")
print(answer2)

latency_table = pd.DataFrame([
    {
        "Pipeline": "Baseline",
        "Bi-encoder retrieval (s)": baseline_retrieval_time,
        "Cross-encoder reranking (s)": 0.0,
        "LLM generation (s)": baseline_llm_time,
        "Total end-to-end (s)": baseline_total_time
    },
    {
        "Pipeline": "Baseline + Cross-Encoder",
        "Bi-encoder retrieval (s)": advanced_retrieval_time,
        "Cross-encoder reranking (s)": advanced_reranking_time,
        "LLM generation (s)": reranked_llm_time,
        "Total end-to-end (s)": reranked_total_time
    }
])
display(latency_table.round(4))

===== ANSWER 1: BASELINE TOP 3 =====

Based on the provided context, when a piece of ice gains 1 or more new subroutines during an encounter with it, those subroutines come into existence unbroken with respect to that encounter. Additionally, if the new subroutine is of a certain category where the number of such subroutines increases, the new copies are added after any previously-existing subroutines in that category.

===== ANSWER 2: CROSS-ENCODER RERANKED TOP 3 =====

Based on the provided context, when a piece of ice gains 1 or more new subroutines during an encounter with it, those subroutines come into existence unbroken with respect to that encounter.

,Pipeline,Bi-encoder retrieval (s),Cross-encoder reranking (s),LLM generation (s),Total end-to-end (s)
0,Baseline,0.0184,0.0000,4.5195,4.5379
1,Baseline + Cross-Encoder,0.0152,1.0064,0.7359,1.7575

## Section 3: Failure-mode analysis

The queries below target document-specific rules, exceptions, and constraints. For each query, the notebook retrieves the same Top 10 candidate set for both approaches, records the baseline rank and cross-encoder rank for every candidate, and shows the Top 3 supplied to the LLM.

**Important:** a query only counts as a successful failure-mode example if the baseline Top 3 misses or inadequately represents the critical rule and re-ranking promotes the relevant chunk into its Top 3. Verify the displayed text and answers; do not claim a rank improvement unless the actual run demonstrates it.

In [236]:
import time
import pandas as pd

failure_queries = [
    {
        "type": "Added subroutines / corner case",
        "query": "What happens to subroutines gained during an encounter with ice?"
    },
    {
        "type": "Negation / constraint",
        "query": "Can a subroutine that has already been broken be broken again?"
    },
    {
        "type": "Exception / bypass",
        "query": "When the Runner bypasses a piece of ice, what happens to the encounter and its subroutines?"
    },
    {
        "type": "Targeting already-broken subroutines",
        "query": "Can an ability that breaks subroutines target a subroutine that is already broken?"
    },
    {
        "type": "Fully-broken ice / exception",
        "query": "If a piece of ice gains new subroutines after the Runner has fully broken it, does the Runner lose the fully-broken status, and can breaking those new subroutines fully break it again?"
    },
    {
        "type": "Keyword Trap / Distractor",
        "query": (
            "If the Runner breaks all subroutines on a piece of ice "
            "using abilities from different cards, does any single "
            "card count as having fully broken the ice?"
        )
    },
    {
        "type": "Exceptions & Corner Cases",
        "query": (
            "If a piece of ice gains new subroutines after the Runner "
            "has fully broken it, does breaking those new subroutines "
            "fully break the ice again?"
        )
    },
    {
        "type": "Negation & Constraints",
        "query": (
            "Can an ability that breaks all subroutines be used if "
            "every subroutine on the encountered ice is already broken?"
        )
    },
    {
        "type": "Other Document-Specific Failures",
        "query": (
            "If the encountered ice has no subroutines, when is the "
            "Runner considered to have fully broken it, and does any "
            "card or other object fully break it?"
        )
    },
    {
        "type": "Other Document-Specific Failure",
        "query": "If the Runner bypasses ice after the paid ability window has begun, do any remaining unbroken subroutines resolve?"
    },
    {
        "type": "Exceptions & Corner Cases",
        "query": (
            "If multiple abilities trigger at the same time during a turn, "
            "how is the order of resolving those abilities determined?"
        )
    },
    {
        "type": "Negation & Constraints",
        "query": (
            "What happens if a player attempts an action that violates a "
            "restriction in the game rules, and can that action still resolve?"
        )
    },
    {
        "type": "Keyword Trap / Distractor",
        "query": (
            "If a card effect makes another card unable to be used, does "
            "that mean the affected card is trashed, or does it remain in play?"
        )
    },
    {
        "type": "Out-of-Domain",
        "query": "What is the best opening strategy for winning a game of chess?"
    }
]

failure_results = []
failure_rank_tables = {}

for case in failure_queries:
    test_query = case["query"]
    print("\n" + "=" * 100)
    print(f"TYPE: {case['type']}\nQUERY: {test_query}")

    start = time.perf_counter()
    top10 = baseline_retrieve(test_query, top_k=10)
    retrieval_time = time.perf_counter() - start

    start = time.perf_counter()
    scores = reranker.predict([(test_query, item["text"]) for item in top10])
    reranking_time = time.perf_counter() - start

    reranked_all = sorted(
        [
            {**item, "rerank_score": float(score)}
            for item, score in zip(top10, scores)
        ],
        key=lambda item: item["rerank_score"],
        reverse=True
    )

    cross_ranks = {
        item["chunk_id"]: rank
        for rank, item in enumerate(reranked_all, start=1)
    }

    cross_scores_by_id = {
        item["chunk_id"]: item["rerank_score"]
        for item in reranked_all
    }

    rank_table = pd.DataFrame([
        {
            "Chunk": item["chunk_id"],
            "PDF page(s)": item.get("pages", [item["page"]]),
            "Baseline rank": rank,
            "Cross-encoder rank": cross_ranks[item["chunk_id"]],
            "Bi-encoder score": round(item["score"], 4),
            "Cross-encoder score": round( cross_scores_by_id[item["chunk_id"]], 4)
        }
        for rank, item in enumerate(top10, start=1)
    ])
    failure_rank_tables[test_query] = rank_table

    baseline_top3 = top10[:3]
    reranked_top3 = reranked_all[:3]

    print("\nRank changes (Cross-encoder rank is within the original Top 10):")
    display(rank_table)
    print("Baseline Top 3 chunk IDs:", [x["chunk_id"] for x in baseline_top3])
    print("Re-ranked Top 3 chunk IDs:", [x["chunk_id"] for x in reranked_top3])
    print(f"Bi-encoder retrieval time: {retrieval_time:.4f} s")
    print(f"Cross-encoder reranking time: {reranking_time:.4f} s")

    print("\n--- Baseline Top 3 passages ---")
    for rank, item in enumerate(baseline_top3, start=1):
        print(f"\nRank {rank} | Chunk {item['chunk_id']} | Page(s) {item.get('pages', [item['page']])}")
        print(item["text"])

    print("\n--- Re-ranked Top 3 passages ---")
    for rank, item in enumerate(reranked_top3, start=1):
        print(f"\nRank {rank} | Chunk {item['chunk_id']} | Page(s) {item.get('pages', [item['page']])}")
        print(item["text"])

    failure_results.append({
        "Failure type": case["type"],
        "Query": test_query,
        "Baseline Top 3": [x["chunk_id"] for x in baseline_top3],
        "Re-ranked Top 3": [x["chunk_id"] for x in reranked_top3],
        "Retrieval time (s)": retrieval_time,
        "Reranking time (s)": reranking_time
    })

failure_summary = pd.DataFrame(failure_results)
display(failure_summary)

====================================================================================================
TYPE: Added subroutines / corner case
QUERY: What happens to subroutines gained during an encounter with ice?

Rank changes (Cross-encoder rank is within the original Top 10):

,Chunk,PDF page(s),Baseline rank,Cross-encoder rank,Bi-encoder score,Cross-encoder score
0,244,[76],1,7,0.7272,4.3738
1,139,[46],2,5,0.6936,4.8798
2,246,[77],3,1,0.6899,7.3383
3,138,"[45, 46]",4,2,0.6846,5.7131
4,149,[49],5,3,0.6581,5.3986
5,240,"[75, 76]",6,9,0.6385,-1.1277
6,312,[97],7,10,0.6217,-5.0897
7,137,[45],8,4,0.6053,5.1560
8,241,[76],9,8,0.5887,3.3387
9,242,[76],10,6,0.5845,4.7895

Baseline Top 3 chunk IDs: [244, 139, 246]
Re-ranked Top 3 chunk IDs: [246, 138, 149]
Bi-encoder retrieval time: 0.0184 s
Cross-encoder reranking time: 0.9974 s

--- Baseline Top 3 passages ---

Rank 1 | Chunk 244 | Page(s) [76]
subroutines are added after other subroutines or does not specify an order. Subroutines in
this category on a single piece of ice are always identical. If the number of such subroutines
increases, the new copies are added after any previously-existing subroutines in this category.
If the number of such subroutines decreases, subroutines are lost beginning with the last
subroutine the ice previously had from the same ability and working backwards.
Example: The Corp has 3 cards in HQ while the Runner is encountering Ashigaru. After the
Runner breaks Ashigaru’s 3 subroutines, the Corp uses Panic Button to draw another card. The
new subroutine is added after the previous 3, so the Runner can use Gbahali to break it.
76

Rank 2 | Chunk 139 | Page(s) [46]
6.9.3c never occurring, meaning that subroutines on the encountered ice are neither broken
nor resolved.
c. A few bypass effects can be triggered later. If ice is bypassed in step 6.9.3b, subroutines
may or may not have been broken, but step 6.9.3c never occurs so no subroutines resolve.
Note that for ice with zero subroutines, the Runner has “broken all subroutines” if and only if
step 6.9.3b was reached. See rule 9.12.2d.
Example: The Runner plays Forked and encounters a Troll that they can bypass with Femme
Fatale. The Runner pays 0credit
to bypass the Troll with Femme Fatale. Forked does not meet its
trigger condition, and Troll is not trashed, because the opportunity to break subroutines was
never reached.

Rank 3 | Chunk 246 | Page(s) [77]
9.8.4. For each encounter, the subroutines on the encountered ice have a status ofBROKEN or UNBROKEN
with respect to that encounter.
a. When an encounter begins, each of the encountered ice’s subroutines becomes unbroken
with respect to that encounter.
b. When a piece of ice gains 1 or more new subroutines during an encounter with it, those
subroutines come into existence unbroken with respect to that encounter.
c. When an encounter ends, card abilities can still check whether subroutines were broken or
unbroken during that encounter.

9.8.5. To BREAK a subroutine is to change its status with respect to the active encounter from unbroken to
broken. Many cards that can allow a player to break subroutines are icebreakers (seesection 3.9.5).
If the Runner breaks all the subroutines on the encountered ice, they fully break that ice (see
section 6.5.7).

--- Re-ranked Top 3 passages ---

Rank 1 | Chunk 246 | Page(s) [77]
9.8.4. For each encounter, the subroutines on the encountered ice have a status ofBROKEN or UNBROKEN
with respect to that encounter.
a. When an encounter begins, each of the encountered ice’s subroutines becomes unbroken
with respect to that encounter.
b. When a piece of ice gains 1 or more new subroutines during an encounter with it, those
subroutines come into existence unbroken with respect to that encounter.
c. When an encounter ends, card abilities can still check whether subroutines were broken or
unbroken during that encounter.

9.8.5. To BREAK a subroutine is to change its status with respect to the active encounter from unbroken to
broken. Many cards that can allow a player to break subroutines are icebreakers (seesection 3.9.5).
If the Runner breaks all the subroutines on the encountered ice, they fully break that ice (see
section 6.5.7).

Rank 2 | Chunk 138 | Page(s) [45, 46]
6.5.5. After the paid ability window in the Encounter Ice Phase closes, unbroken subroutines on the
encountered ice resolve. See section 9.8.7.
45

6.5.6. At the end of the Encounter Ice Phase, the run continues to the Movement Phase, section 6.6.

6.5.7. Fully Break
a. During each encounter, the Runner FULLY BREAKS the encountered ice the first time all
subroutines on that ice are broken.
b. Whenever the Runner fully breaks a piece of ice, if all its subroutines were broken using
abilities on a single object, that object also FULLY BREAKS the ice.
c. If an encountered piece of ice has no subroutines, the Runner fully breaks it whenstep 6.9.3b
of the encounter begins. No objects fully break the ice in this case.
d. If the encountered piece of ice gains subroutines after the Runner fully breaks it, the Runner’s
status of having fully broken the ice remains in place. Conditions that check whether the
Runner fully broke the ice will still be met as normal. Breaking the new subroutines will not
fully break the ice or meet related conditions again.

6.5.8. Bypass
a. When an effect allows the Runner toBYPASSa piece of ice, the Encounter Ice Phase is aborted
and the Runner immediately proceeds to pass that ice.
b. Most bypass effects occur at the beginning of an encounter and result in steps 6.9.3b and

Rank 3 | Chunk 149 | Page(s) [49]
6.9.3. Encounter Ice Phase
a. The encounter begins. Conditions related to the Runner encountering this ice are met.
b. A paid ability window occurs, in which players may only use paid abilities. Subroutines on the
encountered ice can be broken during this window. (P)
c. If there are unbroken subroutines that have not yet resolved this encounter, the Corp resolves
the next such subroutine in order. Otherwise, skip to (e).
d. Return to (c).
e. The Encounter Ice Phase is complete. Continue to step 6.9.4, Movement Phase.

====================================================================================================
TYPE: Negation / constraint
QUERY: Can a subroutine that has already been broken be broken again?

Rank changes (Cross-encoder rank is within the original Top 10):

,Chunk,PDF page(s),Baseline rank,Cross-encoder rank,Bi-encoder score,Cross-encoder score
0,246,[77],1,4,0.6632,5.1523
1,247,[77],2,2,0.6185,6.8427
2,139,[46],3,1,0.5685,7.1767
3,138,"[45, 46]",4,6,0.5201,3.9920
4,244,[76],5,5,0.4858,4.1145
5,131,[44],6,7,0.4827,2.4237
6,249,[78],7,9,0.4577,0.4668
7,240,"[75, 76]",8,10,0.4555,-6.6797
8,248,"[77, 78]",9,8,0.4306,2.1804
9,245,[77],10,3,0.4193,5.4332

Baseline Top 3 chunk IDs: [246, 247, 139]
Re-ranked Top 3 chunk IDs: [139, 247, 245]
Bi-encoder retrieval time: 0.0154 s
Cross-encoder reranking time: 0.7643 s

--- Baseline Top 3 passages ---

Rank 1 | Chunk 246 | Page(s) [77]
9.8.4. For each encounter, the subroutines on the encountered ice have a status ofBROKEN or UNBROKEN
with respect to that encounter.
a. When an encounter begins, each of the encountered ice’s subroutines becomes unbroken
with respect to that encounter.
b. When a piece of ice gains 1 or more new subroutines during an encounter with it, those
subroutines come into existence unbroken with respect to that encounter.
c. When an encounter ends, card abilities can still check whether subroutines were broken or
unbroken during that encounter.

9.8.5. To BREAK a subroutine is to change its status with respect to the active encounter from unbroken to
broken. Many cards that can allow a player to break subroutines are icebreakers (seesection 3.9.5).
If the Runner breaks all the subroutines on the encountered ice, they fully break that ice (see
section 6.5.7).

Rank 2 | Chunk 247 | Page(s) [77]
9.8.6. Only unbroken subroutines can be chosen as targets for abilities that would break them.
a. An ability that breaks “all subroutines” does not target any subroutines, and can be used as
long as the encountered ice has at least 1 unbroken subroutine.
b. One card, Grappling Hook, has the ability to break “all but 1 subroutine” on the encountered
ice. To trigger this ability, its controller chooses as its target the 1 subroutine that will not
be broken. When the ability resolves, it breaks all unbroken subroutines except the chosen
subroutine.
Example: The Runner uses two copies of Grappling Hook to break all of the subroutines on
Heimdall 1.0. For the first Grappling Hook, the Runner chooses the unbroken “sub
 Do 1 core
damage.” subroutine as the target, and Grappling Hook breaks both “sub
 End the run.”
subroutines. For the second Grappling Hook, the Runner chooses one of the already-broken
“sub
 End the run.” subroutines as the target. They can choose the broken subroutine as
Grappling Hook’s target because Grappling Hook will not attempt to break the chosen
subroutine. When the ability resolves, Grappling Hook breaks the “sub
 Do 1 core damage.”
subroutine, but does nothing to the other “sub
 End the run.” subroutine, because it is already
broken.

Rank 3 | Chunk 139 | Page(s) [46]
6.9.3c never occurring, meaning that subroutines on the encountered ice are neither broken
nor resolved.
c. A few bypass effects can be triggered later. If ice is bypassed in step 6.9.3b, subroutines
may or may not have been broken, but step 6.9.3c never occurs so no subroutines resolve.
Note that for ice with zero subroutines, the Runner has “broken all subroutines” if and only if
step 6.9.3b was reached. See rule 9.12.2d.
Example: The Runner plays Forked and encounters a Troll that they can bypass with Femme
Fatale. The Runner pays 0credit
to bypass the Troll with Femme Fatale. Forked does not meet its
trigger condition, and Troll is not trashed, because the opportunity to break subroutines was
never reached.

--- Re-ranked Top 3 passages ---

Rank 1 | Chunk 139 | Page(s) [46]
6.9.3c never occurring, meaning that subroutines on the encountered ice are neither broken
nor resolved.
c. A few bypass effects can be triggered later. If ice is bypassed in step 6.9.3b, subroutines
may or may not have been broken, but step 6.9.3c never occurs so no subroutines resolve.
Note that for ice with zero subroutines, the Runner has “broken all subroutines” if and only if
step 6.9.3b was reached. See rule 9.12.2d.
Example: The Runner plays Forked and encounters a Troll that they can bypass with Femme
Fatale. The Runner pays 0credit
to bypass the Troll with Femme Fatale. Forked does not meet its
trigger condition, and Troll is not trashed, because the opportunity to break subroutines was
never reached.

Rank 2 | Chunk 247 | Page(s) [77]
9.8.6. Only unbroken subroutines can be chosen as targets for abilities that would break them.
a. An ability that breaks “all subroutines” does not target any subroutines, and can be used as
long as the encountered ice has at least 1 unbroken subroutine.
b. One card, Grappling Hook, has the ability to break “all but 1 subroutine” on the encountered
ice. To trigger this ability, its controller chooses as its target the 1 subroutine that will not
be broken. When the ability resolves, it breaks all unbroken subroutines except the chosen
subroutine.
Example: The Runner uses two copies of Grappling Hook to break all of the subroutines on
Heimdall 1.0. For the first Grappling Hook, the Runner chooses the unbroken “sub
 Do 1 core
damage.” subroutine as the target, and Grappling Hook breaks both “sub
 End the run.”
subroutines. For the second Grappling Hook, the Runner chooses one of the already-broken
“sub
 End the run.” subroutines as the target. They can choose the broken subroutine as
Grappling Hook’s target because Grappling Hook will not attempt to break the chosen
subroutine. When the ability resolves, Grappling Hook breaks the “sub
 Do 1 core damage.”
subroutine, but does nothing to the other “sub
 End the run.” subroutine, because it is already
broken.

Rank 3 | Chunk 245 | Page(s) [77]
Example: The Corp has 3 cards in HQ while the Runner is encountering Ashigaru. The Runner
breaks the first subroutine, then uses Utopia Shard to force the Corp to discard 2 cards. Ashigaru
correspondingly loses its last 2 subroutines, leaving behind the subroutine that was already
broken.
e. Subroutines gained from an ability, except a static ability on the ice itself, where the ability
either states the subroutines are added after other subroutines or does not specify an order.
Subroutines within this category are ordered based on when the effect granting them began
to apply, with the oldest subroutines first.
Example: The Runner encounters Marker, and its subroutine resolves. The next ice the Runner
encounters is Brainstorm. When the encounter begins, the lingering effect from Marker gives
Brainstorm an “sub
 End the run.” subroutine. Then, Brainstorm’s conditional ability resolves,
giving it the appropriate number of “sub
 Do 1 core damage.” subroutines. The “sub
 Do 1 core
damage.” subroutines are all ordered after the “sub
 End the run.” subroutine.

====================================================================================================
TYPE: Exception / bypass
QUERY: When the Runner bypasses a piece of ice, what happens to the encounter and its subroutines?

Rank changes (Cross-encoder rank is within the original Top 10):

,Chunk,PDF page(s),Baseline rank,Cross-encoder rank,Bi-encoder score,Cross-encoder score
0,138,"[45, 46]",1,1,0.7346,6.5154
1,149,[49],2,4,0.7035,4.4011
2,133,[44],3,9,0.7027,2.3965
3,137,[45],4,6,0.6652,3.8736
4,132,[44],5,5,0.6617,4.2540
5,141,"[46, 47]",6,8,0.6608,3.0122
6,140,[46],7,7,0.6599,3.7881
7,139,[46],8,2,0.6578,6.4894
8,246,[77],9,3,0.6509,5.0331
9,312,[97],10,10,0.6449,-0.5453

Baseline Top 3 chunk IDs: [138, 149, 133]
Re-ranked Top 3 chunk IDs: [138, 139, 246]
Bi-encoder retrieval time: 0.0175 s
Cross-encoder reranking time: 0.9413 s

--- Baseline Top 3 passages ---

Rank 1 | Chunk 138 | Page(s) [45, 46]
6.5.5. After the paid ability window in the Encounter Ice Phase closes, unbroken subroutines on the
encountered ice resolve. See section 9.8.7.
45

6.5.6. At the end of the Encounter Ice Phase, the run continues to the Movement Phase, section 6.6.

6.5.7. Fully Break
a. During each encounter, the Runner FULLY BREAKS the encountered ice the first time all
subroutines on that ice are broken.
b. Whenever the Runner fully breaks a piece of ice, if all its subroutines were broken using
abilities on a single object, that object also FULLY BREAKS the ice.
c. If an encountered piece of ice has no subroutines, the Runner fully breaks it whenstep 6.9.3b
of the encounter begins. No objects fully break the ice in this case.
d. If the encountered piece of ice gains subroutines after the Runner fully breaks it, the Runner’s
status of having fully broken the ice remains in place. Conditions that check whether the
Runner fully broke the ice will still be met as normal. Breaking the new subroutines will not
fully break the ice or meet related conditions again.

6.5.8. Bypass
a. When an effect allows the Runner toBYPASSa piece of ice, the Encounter Ice Phase is aborted
and the Runner immediately proceeds to pass that ice.
b. Most bypass effects occur at the beginning of an encounter and result in steps 6.9.3b and

Rank 2 | Chunk 149 | Page(s) [49]
6.9.3. Encounter Ice Phase
a. The encounter begins. Conditions related to the Runner encountering this ice are met.
b. A paid ability window occurs, in which players may only use paid abilities. Subroutines on the
encountered ice can be broken during this window. (P)
c. If there are unbroken subroutines that have not yet resolved this encounter, the Corp resolves
the next such subroutine in order. Otherwise, skip to (e).
d. Return to (c).
e. The Encounter Ice Phase is complete. Continue to step 6.9.4, Movement Phase.

Rank 3 | Chunk 133 | Page(s) [44]
The Runner will approach the new ice.
Example: The Runner passes a piece of ice, and in step 6.9.4b, the Corp uses Project Yagi-Uda
to swap that ice with another piece of ice. The Runner has still passed their position (but has not
passed the new ice occupying that position) and will proceed to the next position instep 6.9.4d.
They will not approach or encounter the new ice.

--- Re-ranked Top 3 passages ---

Rank 1 | Chunk 138 | Page(s) [45, 46]
6.5.5. After the paid ability window in the Encounter Ice Phase closes, unbroken subroutines on the
encountered ice resolve. See section 9.8.7.
45

6.5.6. At the end of the Encounter Ice Phase, the run continues to the Movement Phase, section 6.6.

6.5.7. Fully Break
a. During each encounter, the Runner FULLY BREAKS the encountered ice the first time all
subroutines on that ice are broken.
b. Whenever the Runner fully breaks a piece of ice, if all its subroutines were broken using
abilities on a single object, that object also FULLY BREAKS the ice.
c. If an encountered piece of ice has no subroutines, the Runner fully breaks it whenstep 6.9.3b
of the encounter begins. No objects fully break the ice in this case.
d. If the encountered piece of ice gains subroutines after the Runner fully breaks it, the Runner’s
status of having fully broken the ice remains in place. Conditions that check whether the
Runner fully broke the ice will still be met as normal. Breaking the new subroutines will not
fully break the ice or meet related conditions again.

6.5.8. Bypass
a. When an effect allows the Runner toBYPASSa piece of ice, the Encounter Ice Phase is aborted
and the Runner immediately proceeds to pass that ice.
b. Most bypass effects occur at the beginning of an encounter and result in steps 6.9.3b and

Rank 2 | Chunk 139 | Page(s) [46]
6.9.3c never occurring, meaning that subroutines on the encountered ice are neither broken
nor resolved.
c. A few bypass effects can be triggered later. If ice is bypassed in step 6.9.3b, subroutines
may or may not have been broken, but step 6.9.3c never occurs so no subroutines resolve.
Note that for ice with zero subroutines, the Runner has “broken all subroutines” if and only if
step 6.9.3b was reached. See rule 9.12.2d.
Example: The Runner plays Forked and encounters a Troll that they can bypass with Femme
Fatale. The Runner pays 0credit
to bypass the Troll with Femme Fatale. Forked does not meet its
trigger condition, and Troll is not trashed, because the opportunity to break subroutines was
never reached.

Rank 3 | Chunk 246 | Page(s) [77]
9.8.4. For each encounter, the subroutines on the encountered ice have a status ofBROKEN or UNBROKEN
with respect to that encounter.
a. When an encounter begins, each of the encountered ice’s subroutines becomes unbroken
with respect to that encounter.
b. When a piece of ice gains 1 or more new subroutines during an encounter with it, those
subroutines come into existence unbroken with respect to that encounter.
c. When an encounter ends, card abilities can still check whether subroutines were broken or
unbroken during that encounter.

9.8.5. To BREAK a subroutine is to change its status with respect to the active encounter from unbroken to
broken. Many cards that can allow a player to break subroutines are icebreakers (seesection 3.9.5).
If the Runner breaks all the subroutines on the encountered ice, they fully break that ice (see
section 6.5.7).

====================================================================================================
TYPE: Targeting already-broken subroutines
QUERY: Can an ability that breaks subroutines target a subroutine that is already broken?

Rank changes (Cross-encoder rank is within the original Top 10):

,Chunk,PDF page(s),Baseline rank,Cross-encoder rank,Bi-encoder score,Cross-encoder score
0,247,[77],1,1,0.7165,9.6270
1,246,[77],2,3,0.6525,5.8405
2,139,[46],3,4,0.5630,5.3546
3,138,"[45, 46]",4,6,0.5398,4.6684
4,240,"[75, 76]",5,10,0.5301,0.6692
5,249,[78],6,9,0.5104,1.8639
6,245,[77],7,2,0.5090,6.8047
7,201,[65],8,8,0.4945,3.1545
8,131,[44],9,7,0.4678,3.3124
9,244,[76],10,5,0.4598,5.2510

Baseline Top 3 chunk IDs: [247, 246, 139]
Re-ranked Top 3 chunk IDs: [247, 245, 246]
Bi-encoder retrieval time: 0.0163 s
Cross-encoder reranking time: 0.7690 s

--- Baseline Top 3 passages ---

Rank 1 | Chunk 247 | Page(s) [77]
9.8.6. Only unbroken subroutines can be chosen as targets for abilities that would break them.
a. An ability that breaks “all subroutines” does not target any subroutines, and can be used as
long as the encountered ice has at least 1 unbroken subroutine.
b. One card, Grappling Hook, has the ability to break “all but 1 subroutine” on the encountered
ice. To trigger this ability, its controller chooses as its target the 1 subroutine that will not
be broken. When the ability resolves, it breaks all unbroken subroutines except the chosen
subroutine.
Example: The Runner uses two copies of Grappling Hook to break all of the subroutines on
Heimdall 1.0. For the first Grappling Hook, the Runner chooses the unbroken “sub
 Do 1 core
damage.” subroutine as the target, and Grappling Hook breaks both “sub
 End the run.”
subroutines. For the second Grappling Hook, the Runner chooses one of the already-broken
“sub
 End the run.” subroutines as the target. They can choose the broken subroutine as
Grappling Hook’s target because Grappling Hook will not attempt to break the chosen
subroutine. When the ability resolves, Grappling Hook breaks the “sub
 Do 1 core damage.”
subroutine, but does nothing to the other “sub
 End the run.” subroutine, because it is already
broken.

Rank 2 | Chunk 246 | Page(s) [77]
9.8.4. For each encounter, the subroutines on the encountered ice have a status ofBROKEN or UNBROKEN
with respect to that encounter.
a. When an encounter begins, each of the encountered ice’s subroutines becomes unbroken
with respect to that encounter.
b. When a piece of ice gains 1 or more new subroutines during an encounter with it, those
subroutines come into existence unbroken with respect to that encounter.
c. When an encounter ends, card abilities can still check whether subroutines were broken or
unbroken during that encounter.

9.8.5. To BREAK a subroutine is to change its status with respect to the active encounter from unbroken to
broken. Many cards that can allow a player to break subroutines are icebreakers (seesection 3.9.5).
If the Runner breaks all the subroutines on the encountered ice, they fully break that ice (see
section 6.5.7).

Rank 3 | Chunk 139 | Page(s) [46]
6.9.3c never occurring, meaning that subroutines on the encountered ice are neither broken
nor resolved.
c. A few bypass effects can be triggered later. If ice is bypassed in step 6.9.3b, subroutines
may or may not have been broken, but step 6.9.3c never occurs so no subroutines resolve.
Note that for ice with zero subroutines, the Runner has “broken all subroutines” if and only if
step 6.9.3b was reached. See rule 9.12.2d.
Example: The Runner plays Forked and encounters a Troll that they can bypass with Femme
Fatale. The Runner pays 0credit
to bypass the Troll with Femme Fatale. Forked does not meet its
trigger condition, and Troll is not trashed, because the opportunity to break subroutines was
never reached.

--- Re-ranked Top 3 passages ---

Rank 1 | Chunk 247 | Page(s) [77]
9.8.6. Only unbroken subroutines can be chosen as targets for abilities that would break them.
a. An ability that breaks “all subroutines” does not target any subroutines, and can be used as
long as the encountered ice has at least 1 unbroken subroutine.
b. One card, Grappling Hook, has the ability to break “all but 1 subroutine” on the encountered
ice. To trigger this ability, its controller chooses as its target the 1 subroutine that will not
be broken. When the ability resolves, it breaks all unbroken subroutines except the chosen
subroutine.
Example: The Runner uses two copies of Grappling Hook to break all of the subroutines on
Heimdall 1.0. For the first Grappling Hook, the Runner chooses the unbroken “sub
 Do 1 core
damage.” subroutine as the target, and Grappling Hook breaks both “sub
 End the run.”
subroutines. For the second Grappling Hook, the Runner chooses one of the already-broken
“sub
 End the run.” subroutines as the target. They can choose the broken subroutine as
Grappling Hook’s target because Grappling Hook will not attempt to break the chosen
subroutine. When the ability resolves, Grappling Hook breaks the “sub
 Do 1 core damage.”
subroutine, but does nothing to the other “sub
 End the run.” subroutine, because it is already
broken.

Rank 2 | Chunk 245 | Page(s) [77]
Example: The Corp has 3 cards in HQ while the Runner is encountering Ashigaru. The Runner
breaks the first subroutine, then uses Utopia Shard to force the Corp to discard 2 cards. Ashigaru
correspondingly loses its last 2 subroutines, leaving behind the subroutine that was already
broken.
e. Subroutines gained from an ability, except a static ability on the ice itself, where the ability
either states the subroutines are added after other subroutines or does not specify an order.
Subroutines within this category are ordered based on when the effect granting them began
to apply, with the oldest subroutines first.
Example: The Runner encounters Marker, and its subroutine resolves. The next ice the Runner
encounters is Brainstorm. When the encounter begins, the lingering effect from Marker gives
Brainstorm an “sub
 End the run.” subroutine. Then, Brainstorm’s conditional ability resolves,
giving it the appropriate number of “sub
 Do 1 core damage.” subroutines. The “sub
 Do 1 core
damage.” subroutines are all ordered after the “sub
 End the run.” subroutine.

Rank 3 | Chunk 246 | Page(s) [77]
9.8.4. For each encounter, the subroutines on the encountered ice have a status ofBROKEN or UNBROKEN
with respect to that encounter.
a. When an encounter begins, each of the encountered ice’s subroutines becomes unbroken
with respect to that encounter.
b. When a piece of ice gains 1 or more new subroutines during an encounter with it, those
subroutines come into existence unbroken with respect to that encounter.
c. When an encounter ends, card abilities can still check whether subroutines were broken or
unbroken during that encounter.

9.8.5. To BREAK a subroutine is to change its status with respect to the active encounter from unbroken to
broken. Many cards that can allow a player to break subroutines are icebreakers (seesection 3.9.5).
If the Runner breaks all the subroutines on the encountered ice, they fully break that ice (see
section 6.5.7).

====================================================================================================
TYPE: Fully-broken ice / exception
QUERY: If a piece of ice gains new subroutines after the Runner has fully broken it, does the Runner lose the fully-broken status, and can breaking those new subroutines fully break it again?

Rank changes (Cross-encoder rank is within the original Top 10):

,Chunk,PDF page(s),Baseline rank,Cross-encoder rank,Bi-encoder score,Cross-encoder score
0,246,[77],1,5,0.7963,4.0087
1,138,"[45, 46]",2,1,0.7886,6.5277
2,244,[76],3,2,0.6790,5.6641
3,139,[46],4,4,0.6698,4.2732
4,247,[77],5,6,0.6676,3.5015
5,131,[44],6,3,0.5855,4.4455
6,312,[97],7,10,0.5707,0.0110
7,149,[49],8,9,0.5703,1.6634
8,128,[43],9,8,0.5600,2.1786
9,133,[44],10,7,0.5587,2.3254

Baseline Top 3 chunk IDs: [246, 138, 244]
Re-ranked Top 3 chunk IDs: [138, 244, 131]
Bi-encoder retrieval time: 0.0217 s
Cross-encoder reranking time: 0.8228 s

--- Baseline Top 3 passages ---

Rank 1 | Chunk 246 | Page(s) [77]
9.8.4. For each encounter, the subroutines on the encountered ice have a status ofBROKEN or UNBROKEN
with respect to that encounter.
a. When an encounter begins, each of the encountered ice’s subroutines becomes unbroken
with respect to that encounter.
b. When a piece of ice gains 1 or more new subroutines during an encounter with it, those
subroutines come into existence unbroken with respect to that encounter.
c. When an encounter ends, card abilities can still check whether subroutines were broken or
unbroken during that encounter.

9.8.5. To BREAK a subroutine is to change its status with respect to the active encounter from unbroken to
broken. Many cards that can allow a player to break subroutines are icebreakers (seesection 3.9.5).
If the Runner breaks all the subroutines on the encountered ice, they fully break that ice (see
section 6.5.7).

Rank 2 | Chunk 138 | Page(s) [45, 46]
6.5.5. After the paid ability window in the Encounter Ice Phase closes, unbroken subroutines on the
encountered ice resolve. See section 9.8.7.
45

6.5.6. At the end of the Encounter Ice Phase, the run continues to the Movement Phase, section 6.6.

6.5.7. Fully Break
a. During each encounter, the Runner FULLY BREAKS the encountered ice the first time all
subroutines on that ice are broken.
b. Whenever the Runner fully breaks a piece of ice, if all its subroutines were broken using
abilities on a single object, that object also FULLY BREAKS the ice.
c. If an encountered piece of ice has no subroutines, the Runner fully breaks it whenstep 6.9.3b
of the encounter begins. No objects fully break the ice in this case.
d. If the encountered piece of ice gains subroutines after the Runner fully breaks it, the Runner’s
status of having fully broken the ice remains in place. Conditions that check whether the
Runner fully broke the ice will still be met as normal. Breaking the new subroutines will not
fully break the ice or meet related conditions again.

6.5.8. Bypass
a. When an effect allows the Runner toBYPASSa piece of ice, the Encounter Ice Phase is aborted
and the Runner immediately proceeds to pass that ice.
b. Most bypass effects occur at the beginning of an encounter and result in steps 6.9.3b and

Rank 3 | Chunk 244 | Page(s) [76]
subroutines are added after other subroutines or does not specify an order. Subroutines in
this category on a single piece of ice are always identical. If the number of such subroutines
increases, the new copies are added after any previously-existing subroutines in this category.
If the number of such subroutines decreases, subroutines are lost beginning with the last
subroutine the ice previously had from the same ability and working backwards.
Example: The Corp has 3 cards in HQ while the Runner is encountering Ashigaru. After the
Runner breaks Ashigaru’s 3 subroutines, the Corp uses Panic Button to draw another card. The
new subroutine is added after the previous 3, so the Runner can use Gbahali to break it.
76

--- Re-ranked Top 3 passages ---

Rank 1 | Chunk 138 | Page(s) [45, 46]
6.5.5. After the paid ability window in the Encounter Ice Phase closes, unbroken subroutines on the
encountered ice resolve. See section 9.8.7.
45

6.5.6. At the end of the Encounter Ice Phase, the run continues to the Movement Phase, section 6.6.

6.5.7. Fully Break
a. During each encounter, the Runner FULLY BREAKS the encountered ice the first time all
subroutines on that ice are broken.
b. Whenever the Runner fully breaks a piece of ice, if all its subroutines were broken using
abilities on a single object, that object also FULLY BREAKS the ice.
c. If an encountered piece of ice has no subroutines, the Runner fully breaks it whenstep 6.9.3b
of the encounter begins. No objects fully break the ice in this case.
d. If the encountered piece of ice gains subroutines after the Runner fully breaks it, the Runner’s
status of having fully broken the ice remains in place. Conditions that check whether the
Runner fully broke the ice will still be met as normal. Breaking the new subroutines will not
fully break the ice or meet related conditions again.

6.5.8. Bypass
a. When an effect allows the Runner toBYPASSa piece of ice, the Encounter Ice Phase is aborted
and the Runner immediately proceeds to pass that ice.
b. Most bypass effects occur at the beginning of an encounter and result in steps 6.9.3b and

Rank 2 | Chunk 244 | Page(s) [76]
subroutines are added after other subroutines or does not specify an order. Subroutines in
this category on a single piece of ice are always identical. If the number of such subroutines
increases, the new copies are added after any previously-existing subroutines in this category.
If the number of such subroutines decreases, subroutines are lost beginning with the last
subroutine the ice previously had from the same ability and working backwards.
Example: The Corp has 3 cards in HQ while the Runner is encountering Ashigaru. After the
Runner breaks Ashigaru’s 3 subroutines, the Corp uses Panic Button to draw another card. The
new subroutine is added after the previous 3, so the Runner can use Gbahali to break it.
76

Rank 3 | Chunk 131 | Page(s) [44]
Example: The Runner encounters Brân 1.0 and breaks its last two subroutines. Brân 1.0’s first
subroutine resolves and the Corp installs a new piece of ice in the next inward position protecting
the server. The Runner will have to approach that new piece of ice later in this run because its
position is inward from their current position.

====================================================================================================
TYPE: Keyword Trap / Distractor
QUERY: If the Runner breaks all subroutines on a piece of ice using abilities from different cards, does any single card count as having fully broken the ice?

Rank changes (Cross-encoder rank is within the original Top 10):

,Chunk,PDF page(s),Baseline rank,Cross-encoder rank,Bi-encoder score,Cross-encoder score
0,138,"[45, 46]",1,3,0.7647,6.0178
1,246,[77],2,4,0.7501,5.1089
2,247,[77],3,1,0.6909,6.4824
3,244,[76],4,2,0.6529,6.0694
4,139,[46],5,5,0.6373,4.0184
5,149,[49],6,6,0.5859,3.0758
6,78,"[26, 27]",7,9,0.5726,-0.4174
7,312,[97],8,10,0.5705,-2.0251
8,87,"[29, 30]",9,8,0.5432,1.4762
9,137,[45],10,7,0.5410,2.1827

Baseline Top 3 chunk IDs: [138, 246, 247]
Re-ranked Top 3 chunk IDs: [247, 244, 138]
Bi-encoder retrieval time: 0.0191 s
Cross-encoder reranking time: 0.8201 s

--- Baseline Top 3 passages ---

Rank 1 | Chunk 138 | Page(s) [45, 46]
6.5.5. After the paid ability window in the Encounter Ice Phase closes, unbroken subroutines on the
encountered ice resolve. See section 9.8.7.
45

6.5.6. At the end of the Encounter Ice Phase, the run continues to the Movement Phase, section 6.6.

6.5.7. Fully Break
a. During each encounter, the Runner FULLY BREAKS the encountered ice the first time all
subroutines on that ice are broken.
b. Whenever the Runner fully breaks a piece of ice, if all its subroutines were broken using
abilities on a single object, that object also FULLY BREAKS the ice.
c. If an encountered piece of ice has no subroutines, the Runner fully breaks it whenstep 6.9.3b
of the encounter begins. No objects fully break the ice in this case.
d. If the encountered piece of ice gains subroutines after the Runner fully breaks it, the Runner’s
status of having fully broken the ice remains in place. Conditions that check whether the
Runner fully broke the ice will still be met as normal. Breaking the new subroutines will not
fully break the ice or meet related conditions again.

6.5.8. Bypass
a. When an effect allows the Runner toBYPASSa piece of ice, the Encounter Ice Phase is aborted
and the Runner immediately proceeds to pass that ice.
b. Most bypass effects occur at the beginning of an encounter and result in steps 6.9.3b and

Rank 2 | Chunk 246 | Page(s) [77]
9.8.4. For each encounter, the subroutines on the encountered ice have a status ofBROKEN or UNBROKEN
with respect to that encounter.
a. When an encounter begins, each of the encountered ice’s subroutines becomes unbroken
with respect to that encounter.
b. When a piece of ice gains 1 or more new subroutines during an encounter with it, those
subroutines come into existence unbroken with respect to that encounter.
c. When an encounter ends, card abilities can still check whether subroutines were broken or
unbroken during that encounter.

9.8.5. To BREAK a subroutine is to change its status with respect to the active encounter from unbroken to
broken. Many cards that can allow a player to break subroutines are icebreakers (seesection 3.9.5).
If the Runner breaks all the subroutines on the encountered ice, they fully break that ice (see
section 6.5.7).

Rank 3 | Chunk 247 | Page(s) [77]
9.8.6. Only unbroken subroutines can be chosen as targets for abilities that would break them.
a. An ability that breaks “all subroutines” does not target any subroutines, and can be used as
long as the encountered ice has at least 1 unbroken subroutine.
b. One card, Grappling Hook, has the ability to break “all but 1 subroutine” on the encountered
ice. To trigger this ability, its controller chooses as its target the 1 subroutine that will not
be broken. When the ability resolves, it breaks all unbroken subroutines except the chosen
subroutine.
Example: The Runner uses two copies of Grappling Hook to break all of the subroutines on
Heimdall 1.0. For the first Grappling Hook, the Runner chooses the unbroken “sub
 Do 1 core
damage.” subroutine as the target, and Grappling Hook breaks both “sub
 End the run.”
subroutines. For the second Grappling Hook, the Runner chooses one of the already-broken
“sub
 End the run.” subroutines as the target. They can choose the broken subroutine as
Grappling Hook’s target because Grappling Hook will not attempt to break the chosen
subroutine. When the ability resolves, Grappling Hook breaks the “sub
 Do 1 core damage.”
subroutine, but does nothing to the other “sub
 End the run.” subroutine, because it is already
broken.

--- Re-ranked Top 3 passages ---

Rank 1 | Chunk 247 | Page(s) [77]
9.8.6. Only unbroken subroutines can be chosen as targets for abilities that would break them.
a. An ability that breaks “all subroutines” does not target any subroutines, and can be used as
long as the encountered ice has at least 1 unbroken subroutine.
b. One card, Grappling Hook, has the ability to break “all but 1 subroutine” on the encountered
ice. To trigger this ability, its controller chooses as its target the 1 subroutine that will not
be broken. When the ability resolves, it breaks all unbroken subroutines except the chosen
subroutine.
Example: The Runner uses two copies of Grappling Hook to break all of the subroutines on
Heimdall 1.0. For the first Grappling Hook, the Runner chooses the unbroken “sub
 Do 1 core
damage.” subroutine as the target, and Grappling Hook breaks both “sub
 End the run.”
subroutines. For the second Grappling Hook, the Runner chooses one of the already-broken
“sub
 End the run.” subroutines as the target. They can choose the broken subroutine as
Grappling Hook’s target because Grappling Hook will not attempt to break the chosen
subroutine. When the ability resolves, Grappling Hook breaks the “sub
 Do 1 core damage.”
subroutine, but does nothing to the other “sub
 End the run.” subroutine, because it is already
broken.

Rank 2 | Chunk 244 | Page(s) [76]
subroutines are added after other subroutines or does not specify an order. Subroutines in
this category on a single piece of ice are always identical. If the number of such subroutines
increases, the new copies are added after any previously-existing subroutines in this category.
If the number of such subroutines decreases, subroutines are lost beginning with the last
subroutine the ice previously had from the same ability and working backwards.
Example: The Corp has 3 cards in HQ while the Runner is encountering Ashigaru. After the
Runner breaks Ashigaru’s 3 subroutines, the Corp uses Panic Button to draw another card. The
new subroutine is added after the previous 3, so the Runner can use Gbahali to break it.
76

Rank 3 | Chunk 138 | Page(s) [45, 46]
6.5.5. After the paid ability window in the Encounter Ice Phase closes, unbroken subroutines on the
encountered ice resolve. See section 9.8.7.
45

6.5.6. At the end of the Encounter Ice Phase, the run continues to the Movement Phase, section 6.6.

6.5.7. Fully Break
a. During each encounter, the Runner FULLY BREAKS the encountered ice the first time all
subroutines on that ice are broken.
b. Whenever the Runner fully breaks a piece of ice, if all its subroutines were broken using
abilities on a single object, that object also FULLY BREAKS the ice.
c. If an encountered piece of ice has no subroutines, the Runner fully breaks it whenstep 6.9.3b
of the encounter begins. No objects fully break the ice in this case.
d. If the encountered piece of ice gains subroutines after the Runner fully breaks it, the Runner’s
status of having fully broken the ice remains in place. Conditions that check whether the
Runner fully broke the ice will still be met as normal. Breaking the new subroutines will not
fully break the ice or meet related conditions again.

6.5.8. Bypass
a. When an effect allows the Runner toBYPASSa piece of ice, the Encounter Ice Phase is aborted
and the Runner immediately proceeds to pass that ice.
b. Most bypass effects occur at the beginning of an encounter and result in steps 6.9.3b and

====================================================================================================
TYPE: Exceptions & Corner Cases
QUERY: If a piece of ice gains new subroutines after the Runner has fully broken it, does breaking those new subroutines fully break the ice again?

Rank changes (Cross-encoder rank is within the original Top 10):

,Chunk,PDF page(s),Baseline rank,Cross-encoder rank,Bi-encoder score,Cross-encoder score
0,138,"[45, 46]",1,1,0.7823,6.5770
1,246,[77],2,3,0.7790,5.2479
2,244,[76],3,2,0.7049,6.1779
3,139,[46],4,5,0.6552,4.2671
4,247,[77],5,6,0.6527,4.0400
5,131,[44],6,4,0.5979,4.9240
6,149,[49],7,8,0.5894,1.5314
7,312,[97],8,10,0.5862,-4.6400
8,133,[44],9,9,0.5811,0.6090
9,137,[45],10,7,0.5638,2.4881

Baseline Top 3 chunk IDs: [138, 246, 244]
Re-ranked Top 3 chunk IDs: [138, 244, 246]
Bi-encoder retrieval time: 0.0210 s
Cross-encoder reranking time: 0.8219 s

--- Baseline Top 3 passages ---

Rank 1 | Chunk 138 | Page(s) [45, 46]
6.5.5. After the paid ability window in the Encounter Ice Phase closes, unbroken subroutines on the
encountered ice resolve. See section 9.8.7.
45

6.5.6. At the end of the Encounter Ice Phase, the run continues to the Movement Phase, section 6.6.

6.5.7. Fully Break
a. During each encounter, the Runner FULLY BREAKS the encountered ice the first time all
subroutines on that ice are broken.
b. Whenever the Runner fully breaks a piece of ice, if all its subroutines were broken using
abilities on a single object, that object also FULLY BREAKS the ice.
c. If an encountered piece of ice has no subroutines, the Runner fully breaks it whenstep 6.9.3b
of the encounter begins. No objects fully break the ice in this case.
d. If the encountered piece of ice gains subroutines after the Runner fully breaks it, the Runner’s
status of having fully broken the ice remains in place. Conditions that check whether the
Runner fully broke the ice will still be met as normal. Breaking the new subroutines will not
fully break the ice or meet related conditions again.

6.5.8. Bypass
a. When an effect allows the Runner toBYPASSa piece of ice, the Encounter Ice Phase is aborted
and the Runner immediately proceeds to pass that ice.
b. Most bypass effects occur at the beginning of an encounter and result in steps 6.9.3b and

Rank 2 | Chunk 246 | Page(s) [77]
9.8.4. For each encounter, the subroutines on the encountered ice have a status ofBROKEN or UNBROKEN
with respect to that encounter.
a. When an encounter begins, each of the encountered ice’s subroutines becomes unbroken
with respect to that encounter.
b. When a piece of ice gains 1 or more new subroutines during an encounter with it, those
subroutines come into existence unbroken with respect to that encounter.
c. When an encounter ends, card abilities can still check whether subroutines were broken or
unbroken during that encounter.

9.8.5. To BREAK a subroutine is to change its status with respect to the active encounter from unbroken to
broken. Many cards that can allow a player to break subroutines are icebreakers (seesection 3.9.5).
If the Runner breaks all the subroutines on the encountered ice, they fully break that ice (see
section 6.5.7).

Rank 3 | Chunk 244 | Page(s) [76]
subroutines are added after other subroutines or does not specify an order. Subroutines in
this category on a single piece of ice are always identical. If the number of such subroutines
increases, the new copies are added after any previously-existing subroutines in this category.
If the number of such subroutines decreases, subroutines are lost beginning with the last
subroutine the ice previously had from the same ability and working backwards.
Example: The Corp has 3 cards in HQ while the Runner is encountering Ashigaru. After the
Runner breaks Ashigaru’s 3 subroutines, the Corp uses Panic Button to draw another card. The
new subroutine is added after the previous 3, so the Runner can use Gbahali to break it.
76

--- Re-ranked Top 3 passages ---

Rank 1 | Chunk 138 | Page(s) [45, 46]
6.5.5. After the paid ability window in the Encounter Ice Phase closes, unbroken subroutines on the
encountered ice resolve. See section 9.8.7.
45

6.5.6. At the end of the Encounter Ice Phase, the run continues to the Movement Phase, section 6.6.

6.5.7. Fully Break
a. During each encounter, the Runner FULLY BREAKS the encountered ice the first time all
subroutines on that ice are broken.
b. Whenever the Runner fully breaks a piece of ice, if all its subroutines were broken using
abilities on a single object, that object also FULLY BREAKS the ice.
c. If an encountered piece of ice has no subroutines, the Runner fully breaks it whenstep 6.9.3b
of the encounter begins. No objects fully break the ice in this case.
d. If the encountered piece of ice gains subroutines after the Runner fully breaks it, the Runner’s
status of having fully broken the ice remains in place. Conditions that check whether the
Runner fully broke the ice will still be met as normal. Breaking the new subroutines will not
fully break the ice or meet related conditions again.

6.5.8. Bypass
a. When an effect allows the Runner toBYPASSa piece of ice, the Encounter Ice Phase is aborted
and the Runner immediately proceeds to pass that ice.
b. Most bypass effects occur at the beginning of an encounter and result in steps 6.9.3b and

Rank 2 | Chunk 244 | Page(s) [76]
subroutines are added after other subroutines or does not specify an order. Subroutines in
this category on a single piece of ice are always identical. If the number of such subroutines
increases, the new copies are added after any previously-existing subroutines in this category.
If the number of such subroutines decreases, subroutines are lost beginning with the last
subroutine the ice previously had from the same ability and working backwards.
Example: The Corp has 3 cards in HQ while the Runner is encountering Ashigaru. After the
Runner breaks Ashigaru’s 3 subroutines, the Corp uses Panic Button to draw another card. The
new subroutine is added after the previous 3, so the Runner can use Gbahali to break it.
76

Rank 3 | Chunk 246 | Page(s) [77]
9.8.4. For each encounter, the subroutines on the encountered ice have a status ofBROKEN or UNBROKEN
with respect to that encounter.
a. When an encounter begins, each of the encountered ice’s subroutines becomes unbroken
with respect to that encounter.
b. When a piece of ice gains 1 or more new subroutines during an encounter with it, those
subroutines come into existence unbroken with respect to that encounter.
c. When an encounter ends, card abilities can still check whether subroutines were broken or
unbroken during that encounter.

9.8.5. To BREAK a subroutine is to change its status with respect to the active encounter from unbroken to
broken. Many cards that can allow a player to break subroutines are icebreakers (seesection 3.9.5).
If the Runner breaks all the subroutines on the encountered ice, they fully break that ice (see
section 6.5.7).

====================================================================================================
TYPE: Negation & Constraints
QUERY: Can an ability that breaks all subroutines be used if every subroutine on the encountered ice is already broken?

Rank changes (Cross-encoder rank is within the original Top 10):

,Chunk,PDF page(s),Baseline rank,Cross-encoder rank,Bi-encoder score,Cross-encoder score
0,246,[77],1,2,0.7820,7.0782
1,247,[77],2,1,0.7390,9.5661
2,138,"[45, 46]",3,4,0.7275,6.5767
3,139,[46],4,3,0.6922,6.7113
4,244,[76],5,7,0.6569,5.6965
5,240,"[75, 76]",6,9,0.6181,-1.3863
6,241,[76],7,8,0.5861,3.7150
7,312,[97],8,10,0.5764,-5.0147
8,149,[49],9,6,0.5760,6.0580
9,245,[77],10,5,0.5448,6.3739

Baseline Top 3 chunk IDs: [246, 247, 138]
Re-ranked Top 3 chunk IDs: [247, 246, 139]
Bi-encoder retrieval time: 0.0192 s
Cross-encoder reranking time: 1.0637 s

--- Baseline Top 3 passages ---

Rank 1 | Chunk 246 | Page(s) [77]
9.8.4. For each encounter, the subroutines on the encountered ice have a status ofBROKEN or UNBROKEN
with respect to that encounter.
a. When an encounter begins, each of the encountered ice’s subroutines becomes unbroken
with respect to that encounter.
b. When a piece of ice gains 1 or more new subroutines during an encounter with it, those
subroutines come into existence unbroken with respect to that encounter.
c. When an encounter ends, card abilities can still check whether subroutines were broken or
unbroken during that encounter.

9.8.5. To BREAK a subroutine is to change its status with respect to the active encounter from unbroken to
broken. Many cards that can allow a player to break subroutines are icebreakers (seesection 3.9.5).
If the Runner breaks all the subroutines on the encountered ice, they fully break that ice (see
section 6.5.7).

Rank 2 | Chunk 247 | Page(s) [77]
9.8.6. Only unbroken subroutines can be chosen as targets for abilities that would break them.
a. An ability that breaks “all subroutines” does not target any subroutines, and can be used as
long as the encountered ice has at least 1 unbroken subroutine.
b. One card, Grappling Hook, has the ability to break “all but 1 subroutine” on the encountered
ice. To trigger this ability, its controller chooses as its target the 1 subroutine that will not
be broken. When the ability resolves, it breaks all unbroken subroutines except the chosen
subroutine.
Example: The Runner uses two copies of Grappling Hook to break all of the subroutines on
Heimdall 1.0. For the first Grappling Hook, the Runner chooses the unbroken “sub
 Do 1 core
damage.” subroutine as the target, and Grappling Hook breaks both “sub
 End the run.”
subroutines. For the second Grappling Hook, the Runner chooses one of the already-broken
“sub
 End the run.” subroutines as the target. They can choose the broken subroutine as
Grappling Hook’s target because Grappling Hook will not attempt to break the chosen
subroutine. When the ability resolves, Grappling Hook breaks the “sub
 Do 1 core damage.”
subroutine, but does nothing to the other “sub
 End the run.” subroutine, because it is already
broken.

Rank 3 | Chunk 138 | Page(s) [45, 46]
6.5.5. After the paid ability window in the Encounter Ice Phase closes, unbroken subroutines on the
encountered ice resolve. See section 9.8.7.
45

6.5.6. At the end of the Encounter Ice Phase, the run continues to the Movement Phase, section 6.6.

6.5.7. Fully Break
a. During each encounter, the Runner FULLY BREAKS the encountered ice the first time all
subroutines on that ice are broken.
b. Whenever the Runner fully breaks a piece of ice, if all its subroutines were broken using
abilities on a single object, that object also FULLY BREAKS the ice.
c. If an encountered piece of ice has no subroutines, the Runner fully breaks it whenstep 6.9.3b
of the encounter begins. No objects fully break the ice in this case.
d. If the encountered piece of ice gains subroutines after the Runner fully breaks it, the Runner’s
status of having fully broken the ice remains in place. Conditions that check whether the
Runner fully broke the ice will still be met as normal. Breaking the new subroutines will not
fully break the ice or meet related conditions again.

6.5.8. Bypass
a. When an effect allows the Runner toBYPASSa piece of ice, the Encounter Ice Phase is aborted
and the Runner immediately proceeds to pass that ice.
b. Most bypass effects occur at the beginning of an encounter and result in steps 6.9.3b and

--- Re-ranked Top 3 passages ---

Rank 1 | Chunk 247 | Page(s) [77]
9.8.6. Only unbroken subroutines can be chosen as targets for abilities that would break them.
a. An ability that breaks “all subroutines” does not target any subroutines, and can be used as
long as the encountered ice has at least 1 unbroken subroutine.
b. One card, Grappling Hook, has the ability to break “all but 1 subroutine” on the encountered
ice. To trigger this ability, its controller chooses as its target the 1 subroutine that will not
be broken. When the ability resolves, it breaks all unbroken subroutines except the chosen
subroutine.
Example: The Runner uses two copies of Grappling Hook to break all of the subroutines on
Heimdall 1.0. For the first Grappling Hook, the Runner chooses the unbroken “sub
 Do 1 core
damage.” subroutine as the target, and Grappling Hook breaks both “sub
 End the run.”
subroutines. For the second Grappling Hook, the Runner chooses one of the already-broken
“sub
 End the run.” subroutines as the target. They can choose the broken subroutine as
Grappling Hook’s target because Grappling Hook will not attempt to break the chosen
subroutine. When the ability resolves, Grappling Hook breaks the “sub
 Do 1 core damage.”
subroutine, but does nothing to the other “sub
 End the run.” subroutine, because it is already
broken.

Rank 2 | Chunk 246 | Page(s) [77]
9.8.4. For each encounter, the subroutines on the encountered ice have a status ofBROKEN or UNBROKEN
with respect to that encounter.
a. When an encounter begins, each of the encountered ice’s subroutines becomes unbroken
with respect to that encounter.
b. When a piece of ice gains 1 or more new subroutines during an encounter with it, those
subroutines come into existence unbroken with respect to that encounter.
c. When an encounter ends, card abilities can still check whether subroutines were broken or
unbroken during that encounter.

9.8.5. To BREAK a subroutine is to change its status with respect to the active encounter from unbroken to
broken. Many cards that can allow a player to break subroutines are icebreakers (seesection 3.9.5).
If the Runner breaks all the subroutines on the encountered ice, they fully break that ice (see
section 6.5.7).

Rank 3 | Chunk 139 | Page(s) [46]
6.9.3c never occurring, meaning that subroutines on the encountered ice are neither broken
nor resolved.
c. A few bypass effects can be triggered later. If ice is bypassed in step 6.9.3b, subroutines
may or may not have been broken, but step 6.9.3c never occurs so no subroutines resolve.
Note that for ice with zero subroutines, the Runner has “broken all subroutines” if and only if
step 6.9.3b was reached. See rule 9.12.2d.
Example: The Runner plays Forked and encounters a Troll that they can bypass with Femme
Fatale. The Runner pays 0credit
to bypass the Troll with Femme Fatale. Forked does not meet its
trigger condition, and Troll is not trashed, because the opportunity to break subroutines was
never reached.

====================================================================================================
TYPE: Other Document-Specific Failures
QUERY: If the encountered ice has no subroutines, when is the Runner considered to have fully broken it, and does any card or other object fully break it?

Rank changes (Cross-encoder rank is within the original Top 10):

,Chunk,PDF page(s),Baseline rank,Cross-encoder rank,Bi-encoder score,Cross-encoder score
0,138,"[45, 46]",1,1,0.8092,6.7309
1,246,[77],2,3,0.7617,5.6978
2,139,[46],3,2,0.6775,6.2031
3,244,[76],4,5,0.6286,4.2632
4,247,[77],5,4,0.6253,5.5104
5,149,[49],6,6,0.6210,4.0596
6,312,[97],7,10,0.6023,-4.6203
7,128,[43],8,8,0.5936,-2.7498
8,131,[44],9,7,0.5891,2.4637
9,133,[44],10,9,0.5860,-2.9244

Baseline Top 3 chunk IDs: [138, 246, 139]
Re-ranked Top 3 chunk IDs: [138, 139, 246]
Bi-encoder retrieval time: 0.0196 s
Cross-encoder reranking time: 0.7879 s

--- Baseline Top 3 passages ---

Rank 1 | Chunk 138 | Page(s) [45, 46]
6.5.5. After the paid ability window in the Encounter Ice Phase closes, unbroken subroutines on the
encountered ice resolve. See section 9.8.7.
45

6.5.6. At the end of the Encounter Ice Phase, the run continues to the Movement Phase, section 6.6.

6.5.7. Fully Break
a. During each encounter, the Runner FULLY BREAKS the encountered ice the first time all
subroutines on that ice are broken.
b. Whenever the Runner fully breaks a piece of ice, if all its subroutines were broken using
abilities on a single object, that object also FULLY BREAKS the ice.
c. If an encountered piece of ice has no subroutines, the Runner fully breaks it whenstep 6.9.3b
of the encounter begins. No objects fully break the ice in this case.
d. If the encountered piece of ice gains subroutines after the Runner fully breaks it, the Runner’s
status of having fully broken the ice remains in place. Conditions that check whether the
Runner fully broke the ice will still be met as normal. Breaking the new subroutines will not
fully break the ice or meet related conditions again.

6.5.8. Bypass
a. When an effect allows the Runner toBYPASSa piece of ice, the Encounter Ice Phase is aborted
and the Runner immediately proceeds to pass that ice.
b. Most bypass effects occur at the beginning of an encounter and result in steps 6.9.3b and

Rank 2 | Chunk 246 | Page(s) [77]
9.8.4. For each encounter, the subroutines on the encountered ice have a status ofBROKEN or UNBROKEN
with respect to that encounter.
a. When an encounter begins, each of the encountered ice’s subroutines becomes unbroken
with respect to that encounter.
b. When a piece of ice gains 1 or more new subroutines during an encounter with it, those
subroutines come into existence unbroken with respect to that encounter.
c. When an encounter ends, card abilities can still check whether subroutines were broken or
unbroken during that encounter.

9.8.5. To BREAK a subroutine is to change its status with respect to the active encounter from unbroken to
broken. Many cards that can allow a player to break subroutines are icebreakers (seesection 3.9.5).
If the Runner breaks all the subroutines on the encountered ice, they fully break that ice (see
section 6.5.7).

Rank 3 | Chunk 139 | Page(s) [46]
6.9.3c never occurring, meaning that subroutines on the encountered ice are neither broken
nor resolved.
c. A few bypass effects can be triggered later. If ice is bypassed in step 6.9.3b, subroutines
may or may not have been broken, but step 6.9.3c never occurs so no subroutines resolve.
Note that for ice with zero subroutines, the Runner has “broken all subroutines” if and only if
step 6.9.3b was reached. See rule 9.12.2d.
Example: The Runner plays Forked and encounters a Troll that they can bypass with Femme
Fatale. The Runner pays 0credit
to bypass the Troll with Femme Fatale. Forked does not meet its
trigger condition, and Troll is not trashed, because the opportunity to break subroutines was
never reached.

--- Re-ranked Top 3 passages ---

Rank 1 | Chunk 138 | Page(s) [45, 46]
6.5.5. After the paid ability window in the Encounter Ice Phase closes, unbroken subroutines on the
encountered ice resolve. See section 9.8.7.
45

6.5.6. At the end of the Encounter Ice Phase, the run continues to the Movement Phase, section 6.6.

6.5.7. Fully Break
a. During each encounter, the Runner FULLY BREAKS the encountered ice the first time all
subroutines on that ice are broken.
b. Whenever the Runner fully breaks a piece of ice, if all its subroutines were broken using
abilities on a single object, that object also FULLY BREAKS the ice.
c. If an encountered piece of ice has no subroutines, the Runner fully breaks it whenstep 6.9.3b
of the encounter begins. No objects fully break the ice in this case.
d. If the encountered piece of ice gains subroutines after the Runner fully breaks it, the Runner’s
status of having fully broken the ice remains in place. Conditions that check whether the
Runner fully broke the ice will still be met as normal. Breaking the new subroutines will not
fully break the ice or meet related conditions again.

6.5.8. Bypass
a. When an effect allows the Runner toBYPASSa piece of ice, the Encounter Ice Phase is aborted
and the Runner immediately proceeds to pass that ice.
b. Most bypass effects occur at the beginning of an encounter and result in steps 6.9.3b and

Rank 2 | Chunk 139 | Page(s) [46]
6.9.3c never occurring, meaning that subroutines on the encountered ice are neither broken
nor resolved.
c. A few bypass effects can be triggered later. If ice is bypassed in step 6.9.3b, subroutines
may or may not have been broken, but step 6.9.3c never occurs so no subroutines resolve.
Note that for ice with zero subroutines, the Runner has “broken all subroutines” if and only if
step 6.9.3b was reached. See rule 9.12.2d.
Example: The Runner plays Forked and encounters a Troll that they can bypass with Femme
Fatale. The Runner pays 0credit
to bypass the Troll with Femme Fatale. Forked does not meet its
trigger condition, and Troll is not trashed, because the opportunity to break subroutines was
never reached.

Rank 3 | Chunk 246 | Page(s) [77]
9.8.4. For each encounter, the subroutines on the encountered ice have a status ofBROKEN or UNBROKEN
with respect to that encounter.
a. When an encounter begins, each of the encountered ice’s subroutines becomes unbroken
with respect to that encounter.
b. When a piece of ice gains 1 or more new subroutines during an encounter with it, those
subroutines come into existence unbroken with respect to that encounter.
c. When an encounter ends, card abilities can still check whether subroutines were broken or
unbroken during that encounter.

9.8.5. To BREAK a subroutine is to change its status with respect to the active encounter from unbroken to
broken. Many cards that can allow a player to break subroutines are icebreakers (seesection 3.9.5).
If the Runner breaks all the subroutines on the encountered ice, they fully break that ice (see
section 6.5.7).

====================================================================================================
TYPE: Other Document-Specific Failure
QUERY: If the Runner bypasses ice after the paid ability window has begun, do any remaining unbroken subroutines resolve?

Rank changes (Cross-encoder rank is within the original Top 10):

,Chunk,PDF page(s),Baseline rank,Cross-encoder rank,Bi-encoder score,Cross-encoder score
0,149,[49],1,2,0.7791,5.8914
1,138,"[45, 46]",2,1,0.7610,7.4570
2,312,[97],3,7,0.7389,1.3251
3,137,[45],4,3,0.6705,4.9797
4,150,[49],5,5,0.6680,2.9529
5,148,"[48, 49]",6,6,0.6486,1.4850
6,139,[46],7,4,0.6416,4.4867
7,246,[77],8,9,0.6401,0.7993
8,240,"[75, 76]",9,10,0.5920,-1.4288
9,244,[76],10,8,0.5818,0.8712

Baseline Top 3 chunk IDs: [149, 138, 312]
Re-ranked Top 3 chunk IDs: [138, 149, 137]
Bi-encoder retrieval time: 0.0187 s
Cross-encoder reranking time: 0.8034 s

--- Baseline Top 3 passages ---

Rank 1 | Chunk 149 | Page(s) [49]
6.9.3. Encounter Ice Phase
a. The encounter begins. Conditions related to the Runner encountering this ice are met.
b. A paid ability window occurs, in which players may only use paid abilities. Subroutines on the
encountered ice can be broken during this window. (P)
c. If there are unbroken subroutines that have not yet resolved this encounter, the Corp resolves
the next such subroutine in order. Otherwise, skip to (e).
d. Return to (c).
e. The Encounter Ice Phase is complete. Continue to step 6.9.4, Movement Phase.

Rank 2 | Chunk 138 | Page(s) [45, 46]
6.5.5. After the paid ability window in the Encounter Ice Phase closes, unbroken subroutines on the
encountered ice resolve. See section 9.8.7.
45

6.5.6. At the end of the Encounter Ice Phase, the run continues to the Movement Phase, section 6.6.

6.5.7. Fully Break
a. During each encounter, the Runner FULLY BREAKS the encountered ice the first time all
subroutines on that ice are broken.
b. Whenever the Runner fully breaks a piece of ice, if all its subroutines were broken using
abilities on a single object, that object also FULLY BREAKS the ice.
c. If an encountered piece of ice has no subroutines, the Runner fully breaks it whenstep 6.9.3b
of the encounter begins. No objects fully break the ice in this case.
d. If the encountered piece of ice gains subroutines after the Runner fully breaks it, the Runner’s
status of having fully broken the ice remains in place. Conditions that check whether the
Runner fully broke the ice will still be met as normal. Breaking the new subroutines will not
fully break the ice or meet related conditions again.

6.5.8. Bypass
a. When an effect allows the Runner toBYPASSa piece of ice, the Encounter Ice Phase is aborted
and the Runner immediately proceeds to pass that ice.
b. Most bypass effects occur at the beginning of an encounter and result in steps 6.9.3b and

Rank 3 | Chunk 312 | Page(s) [97]
11.4 Timing Structure of a Run ( Section 6.9)
1) Initiation Phase
a) The Runner announces the attacked server.
b) The Runner fills their bad publicity fund.
c) The run begins.
d) The Runner’s position is set to the outermost ice, if any.
e) Paid ability window: (P) (R).
f) Does the Runner have a position corresponding to a piece of ice?
i) If yes, go to (2).
ii) If no, go to (4).
2) Approach Ice Phase
a) The Runner approaches ice.
b) Paid ability window: (P) (R) and ice can be rezzed.
c) Is the approached ice rezzed?
i) If yes, go to (3).
ii) If no, go to (4).
3) Encounter Ice Phase
a) The Runner encounters ice.
b) Paid ability window: (P) and subroutines can be broken.
c) Are there unbroken subroutines to resolve?
i) If yes, the Corp resolves the next one.
ii) If no, go to (e).
d) Return to (c).
e) Go to (4).
4) Movement Phase
97

--- Re-ranked Top 3 passages ---

Rank 1 | Chunk 138 | Page(s) [45, 46]
6.5.5. After the paid ability window in the Encounter Ice Phase closes, unbroken subroutines on the
encountered ice resolve. See section 9.8.7.
45

6.5.6. At the end of the Encounter Ice Phase, the run continues to the Movement Phase, section 6.6.

6.5.7. Fully Break
a. During each encounter, the Runner FULLY BREAKS the encountered ice the first time all
subroutines on that ice are broken.
b. Whenever the Runner fully breaks a piece of ice, if all its subroutines were broken using
abilities on a single object, that object also FULLY BREAKS the ice.
c. If an encountered piece of ice has no subroutines, the Runner fully breaks it whenstep 6.9.3b
of the encounter begins. No objects fully break the ice in this case.
d. If the encountered piece of ice gains subroutines after the Runner fully breaks it, the Runner’s
status of having fully broken the ice remains in place. Conditions that check whether the
Runner fully broke the ice will still be met as normal. Breaking the new subroutines will not
fully break the ice or meet related conditions again.

6.5.8. Bypass
a. When an effect allows the Runner toBYPASSa piece of ice, the Encounter Ice Phase is aborted
and the Runner immediately proceeds to pass that ice.
b. Most bypass effects occur at the beginning of an encounter and result in steps 6.9.3b and

Rank 2 | Chunk 149 | Page(s) [49]
6.9.3. Encounter Ice Phase
a. The encounter begins. Conditions related to the Runner encountering this ice are met.
b. A paid ability window occurs, in which players may only use paid abilities. Subroutines on the
encountered ice can be broken during this window. (P)
c. If there are unbroken subroutines that have not yet resolved this encounter, the Corp resolves
the next such subroutine in order. Otherwise, skip to (e).
d. Return to (c).
e. The Encounter Ice Phase is complete. Continue to step 6.9.4, Movement Phase.

Rank 3 | Chunk 137 | Page(s) [45]
6.4.3. The paid ability window in step 6.9.2b of the Approach Ice Phase is the only time the Corp can
normally rez ice. In this window, the Corp only gains the ability to rez the piece of ice being
approached, not any other ice.

6.4.4. When the Approach Ice Phase completes, the run moves either to the Encounter Ice Phase
(section 6.5) or the Movement Phase (section 6.6). If the approached piece of ice is rezzed, the
Runner encounters it next. If the approached piece of ice is unrezzed or if there is no longer ice
installed in that position, then the run moves directly to the Movement Phase.

6.5 Encounter Ice

6.5.1. The ENCOUNTER ICE PHASEgives the Runner the opportunity to interact with the ice in their current
position, then requires the Corp to resolve unbroken subroutines on that ice.

6.5.2. For purposes of meeting trigger conditions, the Runner encountering a piece of ice is equivalent
to the Encounter Ice Phase beginning at that ice’s position. Abilities with this trigger condition
are subject to rule 9.2.8f.

6.5.3. As each encounter begins, each subroutine on the encountered ice gains an “unbroken” status
associated with that encounter. See section 9.8 for details.

6.5.4. During the paid ability window in the Encounter Ice Phase ( step 6.9.3b), the Runner can break
subroutines on the ice. See rule 9.8.5.

====================================================================================================
TYPE: Exceptions & Corner Cases
QUERY: If multiple abilities trigger at the same time during a turn, how is the order of resolving those abilities determined?

Rank changes (Cross-encoder rank is within the original Top 10):

,Chunk,PDF page(s),Baseline rank,Cross-encoder rank,Bi-encoder score,Cross-encoder score
0,194,[63],1,1,0.6135,3.2467
1,272,[84],2,4,0.5495,-0.6095
2,282,[88],3,5,0.5423,-1.3581
3,274,[85],4,10,0.5270,-7.7599
4,238,[75],5,3,0.5118,0.8439
5,245,[77],6,9,0.4887,-6.2282
6,201,[65],7,7,0.4772,-2.2794
7,213,[68],8,6,0.4758,-2.2593
8,1,[1],9,8,0.4667,-5.9815
9,239,[75],10,2,0.4566,1.8276

Baseline Top 3 chunk IDs: [194, 272, 282]
Re-ranked Top 3 chunk IDs: [194, 239, 238]
Bi-encoder retrieval time: 0.0170 s
Cross-encoder reranking time: 0.8995 s

--- Baseline Top 3 passages ---

Rank 1 | Chunk 194 | Page(s) [63]
9.1.2. To RESOLVE AN ABILITYmeans to resolve each of that ability’s instructions in the order they appear.
If an ability contains more than one instruction, a checkpoint occurs between each consecutive
instruction. To RESOLVE AN INSTRUCTION means to carry out that instruction.
a. While resolving an ability, other abilities can meet their conditions. When this happens, a
“chain reaction” is created. The current instruction finishes resolving, then more recent
abilities fully resolve before the next instruction of the original ability. If any other abilities
meet their conditions while resolving the “chained” abilities, then another “chain” is created
before continuing to resolve the previous chained abilities. Resolve each set of chained
abilities one at a time, from the most recently met condition to the oldest, before continuing
with the original ability that started the chain reaction.
Example: The Runner’s identity is Armand “Geist” Walker. They access a Snare! from R&D with
only 2 cards in their grip. Before taking a tag or suffering any net damage, the Runner triggers
Decoy’s ability in order to avoid the tag. Using the Decoy meets the trigger condition of Armand
“Geist” Walker’s ability. As this is the most recent ability to meet its trigger condition, Armand
“Geist” Walker’s ability must resolve first, before Decoy avoids the tag and before Snare! finishes
resolving. The Runner draws a card from Armand “Geist” Walker, avoids the tag from Snare! with
Decoy, and then finally suffers (and survives) the 3 net damage from Snare!.
b. An ability “is resolving” from when its first instruction becomes imminent until its last
instruction has finished resolving. See also section 9.9. An event or operation “is resolving”

Rank 2 | Chunk 272 | Page(s) [84]
out, that part of the ability becomes the next instruction. See also section 1.16.11.
g. If an effect directs a player to choose between a set of options that would create different
effects, that choice ends an instruction. Each option begins its own instruction or set of
instructions, and the one chosen will resolve next.
Example: The Runner encounters Data Raven and is forced by its first ability to resolve either
“take 1 tag” or “end the run.” Making this choice ends the first instruction, and the option the
Runner chooses will become imminent after a checkpoint.

9.11.5. If an ability initiates a timing structure, its source may have linked abilities that apply during that
timing structure. These are frequently written directly after the instruction that creates the timing
structure, but they are not instructions in the same ability.

9.12 Other Rules and Terminology

9.12.1. Simultaneous Effects
84

Rank 3 | Chunk 282 | Page(s) [88]
9.12.6. Modal Abilities
a. Some abilities contain text organized into bulleted lists. These are called MODAL ABILITIES,
and each list item is called a MODE.
b. Each modal ability contains an instruction directing its controller to resolve 1 or more of
its modes. The effect of this instruction is for the relevant player to choose the next mode
to resolve. The first instruction of the chosen mode will be the next instruction to become
imminent. The player does not need to choose modes in the order they are written. If the
description of the number of modes to resolve contains “up to”, the player may also choose
not to resolve any more modes.
c. After the instructions of a mode are complete, the game returns to the instruction to resolve
1 or more modes. If the maximum allowed number of modes have not yet been resolved, the
player will choose another mode to resolve, as if resolving that initial instruction again. If
the maximum number of allowed modes have been resolved, the game proceeds to the next
instruction or ability following the list of modes.
d. In a single instance of resolving a modal ability, each mode can be resolved no more than 1
time, unless the ability specifically states that its modes can be chosen more than once.
10 Additional Rules

10.1 General

--- Re-ranked Top 3 passages ---

Rank 1 | Chunk 194 | Page(s) [63]
9.1.2. To RESOLVE AN ABILITYmeans to resolve each of that ability’s instructions in the order they appear.
If an ability contains more than one instruction, a checkpoint occurs between each consecutive
instruction. To RESOLVE AN INSTRUCTION means to carry out that instruction.
a. While resolving an ability, other abilities can meet their conditions. When this happens, a
“chain reaction” is created. The current instruction finishes resolving, then more recent
abilities fully resolve before the next instruction of the original ability. If any other abilities
meet their conditions while resolving the “chained” abilities, then another “chain” is created
before continuing to resolve the previous chained abilities. Resolve each set of chained
abilities one at a time, from the most recently met condition to the oldest, before continuing
with the original ability that started the chain reaction.
Example: The Runner’s identity is Armand “Geist” Walker. They access a Snare! from R&D with
only 2 cards in their grip. Before taking a tag or suffering any net damage, the Runner triggers
Decoy’s ability in order to avoid the tag. Using the Decoy meets the trigger condition of Armand
“Geist” Walker’s ability. As this is the most recent ability to meet its trigger condition, Armand
“Geist” Walker’s ability must resolve first, before Decoy avoids the tag and before Snare! finishes
resolving. The Runner draws a card from Armand “Geist” Walker, avoids the tag from Snare! with
Decoy, and then finally suffers (and survives) the 3 net damage from Snare!.
b. An ability “is resolving” from when its first instruction becomes imminent until its last
instruction has finished resolving. See also section 9.9. An event or operation “is resolving”

Rank 2 | Chunk 239 | Page(s) [75]
9.7.1. Any ability on an event or operation that is not a paid, conditional, or static ability is a PLAY
ABILITY. Play abilities are the abilities that resolve as part of playing that event or operation during
step 8.6.7f.
Example: The operation card Oppo Research has several abilities of different types. The first ability
reads “Play only if the Runner stole or trashed a Corp card during their last turn.” This is a static ability
that contains a restriction and no declarations. The second ability (“After you resolve this operation, your
action phase ends.”) is a conditional ability that meets its trigger condition and resolves after the Corp
finishes playing and resolving Oppo Research. The third and fourth abilities contain instructions with no
trigger conditions or paid ability trigger costs, so they are both play abilities. They resolve in sequence
while Oppo Research is being played.

Rank 3 | Chunk 238 | Page(s) [75]
9.6.15. Steps of Triggering and Resolving a Conditional Ability
a. Announce that you will trigger one of the pending abilities associated with the reaction
window that gave you priority.
b. Announce any targets for the ability’s first instruction. That instruction then becomes
imminent.
c. An interrupt window occurs, during which abilities can modify, prevent, or avoid the imminent
effects.
d. Resolve the instruction, applying any changes to its effects from interrupts that were
resolved. If the controller of the ability chooses to resolve an optional effect contained in
this instruction, and this is the first instruction for which that player has done so, “when
used” conditionals meet their trigger conditions.
e. A checkpoint occurs.
f. If there are more instructions to resolve, announce any targets for the next instruction. That
instruction then becomes imminent. Return to (c).
g. Resolution of the conditional ability is complete.

9.7 Play Abilities

====================================================================================================
TYPE: Negation & Constraints
QUERY: What happens if a player attempts an action that violates a restriction in the game rules, and can that action still resolve?

Rank changes (Cross-encoder rank is within the original Top 10):

,Chunk,PDF page(s),Baseline rank,Cross-encoder rank,Bi-encoder score,Cross-encoder score
0,212,[68],1,6,0.5250,-5.0915
1,45,[15],2,4,0.4481,-3.0805
2,115,[39],3,2,0.4476,0.5024
3,279,[87],4,3,0.4426,-0.5159
4,160,[52],5,5,0.4371,-4.5160
5,258,[80],6,7,0.4144,-6.2227
6,287,[89],7,10,0.4100,-7.0849
7,170,[55],8,9,0.4084,-6.7025
8,110,[37],9,1,0.4042,0.9687
9,44,[15],10,8,0.3973,-6.2315

Baseline Top 3 chunk IDs: [212, 45, 115]
Re-ranked Top 3 chunk IDs: [110, 115, 279]
Bi-encoder retrieval time: 0.0180 s
Cross-encoder reranking time: 0.9332 s

--- Baseline Top 3 passages ---

Rank 1 | Chunk 212 | Page(s) [68]
9.3.3. A RESTRICTION is a unit of text that applies one of a specific set of constraints for a card to be
played or an ability to be used. If a restriction appears in an ability, it applies to the entire ability
regardless of whether it is written before, after, or in the middle of the ability’s other text. Many
restrictions fall under section 9.1.8, meaning they are active even while their source is inactive.
a. Text modifying the cost to play, install, rez, or steal the card it appears on is a restriction,
including text that adds an additional cost.
b. Constraints on when or where a card can be installed, rezzed, played, or scored are
restrictions.
c. Limits on when, where, or how often an ability can be used are restrictions.
d. Constraints on how a cost can be paid are restrictions.
e. If a card’s text limits what cards it can host, the text describing that limit is a restriction. See
also rule 1.13.6b.
f. Definitions for or constraints on a variable are restrictions.
Example: Some abilities dictate a value for X, such as “X is the number of rezzed NEXT ice.”
Some abilities with X in their cost constrain the value that can be chosen for X, such as “X must
be equal to or less than the number of tags the Runner has.” These statements are restrictions.
g. Stipulations that an effect or part of an effect cannot be prevented are restrictions.
h. Any text not falling under one of the above categories is not a restriction.

Rank 2 | Chunk 45 | Page(s) [15]
1.15.3. At the time an instruction resolves, if any of its targets either have become invalid or were not
announced, as much of that ability resolves as possible without acting on the unannounced or
invalid targets, following rules 1.2.3 and 1.2.4 of the Golden Rules. A target can be invalid because
the chosen object or subroutine no longer exists or because the target no longer meets other
requirements specified by the targeting ability.

1.15.4. After the resolution of an instruction that chose a particular target, subsequent instructions of the
same ability can continue to act on that target without needing to select it again, even if the ability
moves the target or changes its properties. See also section 1.12.2.
Example: Howler’s ability targets a card in HQ. Its first instruction installs that card, and its second
instruction creates a delayed conditional ability that refers to that card in the play area. The latter ability
can find and act on the card as long as it is still installed.

1.16 Costs

Rank 3 | Chunk 115 | Page(s) [39]
5.4.3. A player’s action phase can be forced to end by certain card abilities (e.g. via the ability on a
terminal operation or event). When a player’s action phase is forced to end, the following occurs:
a. The current step of the action phase ends, and all remaining steps are skipped.
b. Any currently open priority windows close, their associated abilities lose their pending status,
and the player with priority loses priority.
c. Any currently resolving actions or abilities cease resolving and are considered complete.
d. Conditions related to the action phase ending are met, and a checkpoint occurs. A reaction
window created by this checkpoint is still considered to be taking place in the action phase,
but players cannot take actions during this window.
e. After completing any reaction windows opened by the checkpoint from rule 5.4.3d, the game
proceeds to the active player’s discard phase.

5.4.4. If an effect attempts to end a player’s action phase during their draw phase, their discard phase,
or another player’s turn, this effect does nothing.

5.5 Discard Phase

5.5.1. The discard phase is the last phase of each player’s turn. It contains the discard step and the
formal end of that player’s turn.

--- Re-ranked Top 3 passages ---

Rank 1 | Chunk 110 | Page(s) [37]
5.2.2. A player initiates an action by paying its cost in click
, as well as any other costs associated with that
action, during their action window.
a. Once an action is initiated, it must be completed before the game can advance to the next
step or open another action window. If the effects of an action initiate a timing structure,
such as a run, players may use paid abilities, rez cards, and score agendas as dictated by the
priority windows of that nested timing structure, but otherwise players cannot perform any of
those voluntary effects while the action is resolving. See section 9.2 for more details about
priority.
b. If a timing structure is initiated during the resolution of an action, that action is not
complete until the new timing structure is complete and any further effects of the initiated
action following the completion of the new timing structure are resolved.
Example: The Runner takes the action “play an event”, playing Stimhack. The action is not
complete until the run initiated by Stimhack ends, the Runner suffers core damage, and Stimhack
is trashed following its resolution.
c. A conditional ability that meets its trigger condition due to a player taking an action resolves
after the action’s trigger cost is paid, before the effects of the action itself. See rule 9.1.2a.
d. Some conditional abilities meet their trigger conditions due to an action “ending”,
“finishing”, or “completing”. These abilities resolve in the reaction window following
step 5.6.2b or step 5.7.1f, for actions taken by the Corp and Runner, respectively.
37

Rank 2 | Chunk 115 | Page(s) [39]
5.4.3. A player’s action phase can be forced to end by certain card abilities (e.g. via the ability on a
terminal operation or event). When a player’s action phase is forced to end, the following occurs:
a. The current step of the action phase ends, and all remaining steps are skipped.
b. Any currently open priority windows close, their associated abilities lose their pending status,
and the player with priority loses priority.
c. Any currently resolving actions or abilities cease resolving and are considered complete.
d. Conditions related to the action phase ending are met, and a checkpoint occurs. A reaction
window created by this checkpoint is still considered to be taking place in the action phase,
but players cannot take actions during this window.
e. After completing any reaction windows opened by the checkpoint from rule 5.4.3d, the game
proceeds to the active player’s discard phase.

5.4.4. If an effect attempts to end a player’s action phase during their draw phase, their discard phase,
or another player’s turn, this effect does nothing.

5.5 Discard Phase

5.5.1. The discard phase is the last phase of each player’s turn. It contains the discard step and the
formal end of that player’s turn.

Rank 3 | Chunk 279 | Page(s) [87]
c. If the “must” ability presents a player with a choice between two or more effects, that player
must choose an effect that can be fully resolved. If none of the choices can be fully resolved,
then the “must” ability does nothing.
Example: If the first subroutine on Fairchild 2.0 resolves while the Runner has no installed cards
but 3credit
, then the Runner must choose to pay 2credit
. When the second subroutine on Fairchild 2.0
resolves, the Runner can neither pay 2credit
nor trash an installed card, so nothing happens.
d. Making a choice between effects is always a separate instruction from resolving the chosen
effect (see rule 9.11.4g). The previous rule only requires the player to choose an effect that
is possible to resolve; it does not require the chosen effect to actually resolve as expected.
Once an effect has been chosen, the player can apply interrupts to modify, prevent, or replace
that effect as normal.
Example: If the Runner encounters Data Raven, they must choose to either take a tag or end the
run. The Runner can choose to take the tag, then avoid the tag with Decoy. This does not cause
the run to end, as the decision to take the tag has already been made.
e. A singular “must” ability cannot force a player to pay an additional cost they wish to decline,
but a player cannot avoid choosing a fully resolvable effect from among multiple options in a
“must” ability by declining to pay the additional cost for one of those choices.
Example: If Service Outage is active and the Runner has Always Be Running installed, the Runner
can decline to pay the additional 1credit
to make a run with their first click
, thus satisfying the “must”
of Always Be Running and allowing them to spend their first click on a different action. However,

====================================================================================================
TYPE: Keyword Trap / Distractor
QUERY: If a card effect makes another card unable to be used, does that mean the affected card is trashed, or does it remain in play?

Rank changes (Cross-encoder rank is within the original Top 10):

,Chunk,PDF page(s),Baseline rank,Cross-encoder rank,Bi-encoder score,Cross-encoder score
0,187,[60],1,1,0.7309,5.5361
1,186,[60],2,2,0.5649,3.7070
2,170,[55],3,6,0.5595,1.5209
3,152,[50],4,9,0.5504,-1.1680
4,283,[88],5,3,0.5493,2.6561
5,281,[87],6,5,0.5421,1.9769
6,294,[91],7,4,0.5253,2.0536
7,107,"[36, 37]",8,10,0.5247,-4.0003
8,32,[11],9,7,0.5138,1.1337
9,116,[39],10,8,0.5008,0.2434

Baseline Top 3 chunk IDs: [187, 186, 170]
Re-ranked Top 3 chunk IDs: [187, 186, 283]
Bi-encoder retrieval time: 0.0185 s
Cross-encoder reranking time: 0.8413 s

--- Baseline Top 3 passages ---

Rank 1 | Chunk 187 | Page(s) [60]
8.6.6. In certain circumstances, a played card is not trashed after resolving it.
a. If the played card is no longer in the play area when step 8.6.7g is reached, it is not trashed.
Example: The Runner plays Ashen Epilogue and resolves its play abilities. Its last ability removes
it from the game.
b. If the played card has been converted to a condition counter or otherwise hosted on a card
while resolving its play abilities, it is not trashed. See also rule 10.1.4.
c. If the played card has an ability indicating that it is not trashed until a certain effect occurs,
instead of trashing it, a lingering effect is created with a duration that expires as the indicated
effect occurs. See also section 9.10.
d. If an ability that plays an event or operation also contains the nested conditional ability “After
it resolves, remove it from the game.”, the event or operation is not trashed. The card remains
in the play area until the conditional ability removes it from the game.

Rank 2 | Chunk 186 | Page(s) [60]
8.6.4. Operations and events can create lingering effects. Once those effects exist, they become
independent of the source operation or event and the card is considered fully resolved and ready
to be trashed. See section 9.10.
Example: Test Run creates a delayed conditional ability that will resolve at the end of the turn, but Test
Run itself is considered fully resolved and is trashed once it finishes installing a program.

8.6.5. An operation or event that initiates a timing structure remains active in the play area for the
duration of that timing structure. It is not considered fully resolved until the timing structure is
completed and any abilities on the card that meet their trigger conditions when the timing structure
ends are resolved.

Rank 3 | Chunk 170 | Page(s) [55]
8.2.2. If a replacement effect modifies the effects of a movement, but does not replace the entire
movement by name, the modified effect is still an occurrence of that movement and can still
meet trigger conditions relating to that type of movement.
Example: Harbinger’s ability modifies the effects of trashing it by replacing adding Harbinger to the
heap with turning it facedown. Harbinger is still trashed when the modified effect resolves. If this is
the first time this turn that the Runner trashed one of their installed cards, they will be able to resolve
Wasteland’s ability.
a. If a movement is replaced or prevented entirely or otherwise cannot be carried out, that
movement does not take place and conditions related to that type of movement are not met.
Example: The Corp is resolving the first subroutine on Rototurret to trash an installed program.
The Runner uses Sacrificial Construct to prevent the program from being trashed. Since trashing
did not occur, the Runner does not place a power counter on District 99, and District 99 can still
meet its trigger condition if a program or piece of hardware is successfully trashed later in the
turn.

8.2.3. To ARRANGE a set of cards is to reposition them among their current locations. The full rules for
arranging are detailed in section 8.3.

--- Re-ranked Top 3 passages ---

Rank 1 | Chunk 187 | Page(s) [60]
8.6.6. In certain circumstances, a played card is not trashed after resolving it.
a. If the played card is no longer in the play area when step 8.6.7g is reached, it is not trashed.
Example: The Runner plays Ashen Epilogue and resolves its play abilities. Its last ability removes
it from the game.
b. If the played card has been converted to a condition counter or otherwise hosted on a card
while resolving its play abilities, it is not trashed. See also rule 10.1.4.
c. If the played card has an ability indicating that it is not trashed until a certain effect occurs,
instead of trashing it, a lingering effect is created with a duration that expires as the indicated
effect occurs. See also section 9.10.
d. If an ability that plays an event or operation also contains the nested conditional ability “After
it resolves, remove it from the game.”, the event or operation is not trashed. The card remains
in the play area until the conditional ability removes it from the game.

Rank 2 | Chunk 186 | Page(s) [60]
8.6.4. Operations and events can create lingering effects. Once those effects exist, they become
independent of the source operation or event and the card is considered fully resolved and ready
to be trashed. See section 9.10.
Example: Test Run creates a delayed conditional ability that will resolve at the end of the turn, but Test
Run itself is considered fully resolved and is trashed once it finishes installing a program.

8.6.5. An operation or event that initiates a timing structure remains active in the play area for the
duration of that timing structure. It is not considered fully resolved until the timing structure is
completed and any abilities on the card that meet their trigger conditions when the timing structure
ends are resolved.

Rank 3 | Chunk 283 | Page(s) [88]
10.1.1. Some cards are UNIQUE, and have a unique symbol (♦) before their name to designate this. There
can be only one unique card of the same name active at a time. If a unique card becomes active,
any other card that shares its name is trashed during the next checkpoint. Trashing a card this
way cannot be prevented. See section 10.3.

10.1.2. To PURGE VIRUS COUNTERS is to remove all virus counters hosted on cards and return them to the
bank. The Corp can purge virus counters as a basic action or with a card ability.

10.1.3. Some abilities add a card to a player’s score area “as an agenda”. When this happens, the card
loses all its previous properties and gains only those properties specified in the effect converting
it. This conversion lasts until the card moves to a zone that is not a score area, at which point it
returns to being its original printed card. If this happens in any way other than by agenda forfeit,
the card is immediately trashed. See rule 8.2.5.

10.1.4. Some abilities can convert a card into a counter. When this happens, the card loses all its previous
properties and gains only those properties specified in the effect converting it. This conversion
lasts until the counter moves to another zone, at which point it reverts to being a card, regains its
original printed characteristics, and is trashed.

====================================================================================================
TYPE: Out-of-Domain
QUERY: What is the best opening strategy for winning a game of chess?

Rank changes (Cross-encoder rank is within the original Top 10):

,Chunk,PDF page(s),Baseline rank,Cross-encoder rank,Bi-encoder score,Cross-encoder score
0,5,"[2, 3]",1,5,0.2974,-10.6435
1,313,[98],2,10,0.2823,-11.2027
2,18,[7],3,2,0.2753,-5.2868
3,148,"[48, 49]",4,7,0.2505,-11.1273
4,141,"[46, 47]",5,6,0.2501,-11.1103
5,19,[7],6,1,0.2488,-5.0245
6,4,[2],7,3,0.2473,-9.5131
7,129,[43],8,8,0.2452,-11.1336
8,144,[47],9,4,0.2390,-10.2805
9,124,[42],10,9,0.2353,-11.1670

Baseline Top 3 chunk IDs: [5, 313, 18]
Re-ranked Top 3 chunk IDs: [19, 18, 4]
Bi-encoder retrieval time: 0.0150 s
Cross-encoder reranking time: 1.2196 s

--- Baseline Top 3 passages ---

Rank 1 | Chunk 5 | Page(s) [2, 3]
6.1 General . . . . . . . . . . . . . . . . . 41

6.2 Position . . . . . . . . . . . . . . . . 42

6.3 Initiation . . . . . . . . . . . . . . . . 44

6.4 Approach Ice . . . . . . . . . . . . . 45

6.5 Encounter Ice . . . . . . . . . . . . . 45

6.5.7 Fully Break . . . . . . . . . . 46

6.5.8 Bypass . . . . . . . . . . . . 46

6.5.9 Forced Encounters . . . . . 46

6.6 Movement . . . . . . . . . . . . . . . 46

6.7 Success . . . . . . . . . . . . . . . . 47

6.8 Run Ends Phase . . . . . . . . . . . 47

6.9 Steps of a Run . . . . . . . . . . . . 48
7 Accessing Cards and Breaching Servers 49

7.1 Accessing Cards . . . . . . . . . . . . 50

7.2 Steps of Accessing a Card . . . . . 50

7.3 Breaching Servers . . . . . . . . . . 51

7.4 Determining Candidates . . . . . . 52

7.5 Steps of Breaching a Server . . . . 54
8 Card Manipulation . . . . . . . . . . . . . 54

8.1 Faceup and Facedown Status . . . . 54

8.2 Card Movements . . . . . . . . . . . 55

8.3 Arranging and Rearranging Cards . 56

8.4 Drawing Cards . . . . . . . . . . . . 56

8.4.5 Steps of Drawing N Cards . 57

8.5 Installing and Uninstalling Cards . 57

8.5.16 Steps of Installing a Card 59

8.6 Playing Events and Operations . . . 59
2

8.6.7 Steps of Playing an Event
or Operation . . . . . . . . . . 60

8.7 Searching for Cards . . . . . . . . . 60

Rank 2 | Chunk 313 | Page(s) [98]
a) If the run got here from (2) or (3), the Runner passes ice.
b) Paid ability window: (P).
c) The Runner may jack out.
d) The Runner moves 1 position inward, if possible.
e) Paid ability window: (P) (R).
f) Did the Runner move to a new position?
i) If yes, go to (2).
ii) If no, go to (g).
g) The Runner approaches the server.
h) Go to (5).
5) Success Phase
a) The run is declared successful.
b) The Runner breaches the attacked server.
c) Go to (6).
6) Run Ends Phase
a) Close or resolve priority windows from before “end the run”.
b) The Runner empties their bad publicity fund.
c) If applicable, the run is declared unsuccessful.
d) The run is complete.

11.5 Timing Structure of Breaching a Server ( Section 7.5)
1) The breach begins.
2) If breaching Archives, facedown cards in Archives are turned faceup.
3) If breaching HQ or R&D, determine how many accesses from Corp’s hand or deck.
4) Are there candidate cards remaining to access?
a) If yes, the Runner chooses a candidate.
b) If no, go to (7).
5) The Runner accesses the chosen card.
6) Return to (4).
7) Breaching the server is complete.

11.6 Timing Structure of Accessing a Card ( Section 7.2)
1) The card is accessed.
2) The Runner may trash the card or use another mid-access ability.
3) If the card is an agenda, the Runner steals it.
4) Access is complete.
98

Rank 3 | Chunk 18 | Page(s) [7]
1.6.6. Each player draws 5 cards from the top of their deck to form their starting hand.
a. After drawing starting hands, the Corp may choose to take a mulligan; then, the Runner may
choose to take a mulligan. To take a mulligan, the player shuffles their starting hand back
into their deck, then draws a new starting hand. They must keep the second hand as their
starting hand.

1.6.7. The game begins and the Corp takes their first turn.
a. If the Corp’s identity has an ability with instructions for “before taking your first turn,” the
Corp resolves that ability immediately before taking their first turn, and thus before the game
starts.

1.7 Ending the Game

1.7.1. The game ends when a player meets one of their win conditions.
a. If both players would simultaneously satisfy their win conditions, the game ends in a draw.

--- Re-ranked Top 3 passages ---

Rank 1 | Chunk 19 | Page(s) [7]
1.7.2. Each player has two possible win conditions available.
a. Either player can win by collecting agenda points in their score area (usually done by scoring
or stealing agendas; see section 1.17). A player with a score of 7 or more wins the game.
b. The Corp wins if the Runner is FLATLINED. The Runner is flatlined immediately if they suffer
more damage than they have cards in their grip. See section 10.4 for information about
damage. The Runner is also flatlined if, at the beginning of their discard step, their maximum
hand size is less than 0. See section 5.5 for information about maximum hand size and the
discard step.
c. The Runner wins if the Corp is required to draw a card from R&D but cannot because R&D is
empty.

1.8 Cards

1.8.1. There are six types of Corp cards: agendas, assets, ice, identities, operations, and upgrades. All
cards except the identity card are shuffled into the Corp’s deck at the beginning of the game.

1.8.2. There are five types of Runner cards: events, hardware, identities, programs, and resources. All
cards except the identity card are shuffled into the Runner’s deck at the beginning of the game.

Rank 2 | Chunk 18 | Page(s) [7]
1.6.6. Each player draws 5 cards from the top of their deck to form their starting hand.
a. After drawing starting hands, the Corp may choose to take a mulligan; then, the Runner may
choose to take a mulligan. To take a mulligan, the player shuffles their starting hand back
into their deck, then draws a new starting hand. They must keep the second hand as their
starting hand.

1.6.7. The game begins and the Corp takes their first turn.
a. If the Corp’s identity has an ability with instructions for “before taking your first turn,” the
Corp resolves that ability immediately before taking their first turn, and thus before the game
starts.

1.7 Ending the Game

1.7.1. The game ends when a player meets one of their win conditions.
a. If both players would simultaneously satisfy their win conditions, the game ends in a draw.

Rank 3 | Chunk 4 | Page(s) [2]
3.10 Resources . . . . . . . . . . . . . . 29
4 Game Zones . . . . . . . . . . . . . . . . . 30

4.1 General . . . . . . . . . . . . . . . . . 30

4.2 Deck . . . . . . . . . . . . . . . . . . 30

4.2.7 R&D . . . . . . . . . . . . . . 31

4.2.8 Stack . . . . . . . . . . . . . 31

4.3 Hand . . . . . . . . . . . . . . . . . . 31

4.3.8 HQ . . . . . . . . . . . . . . . 31

4.3.9 Grip . . . . . . . . . . . . . . 32

4.4 Discard Pile . . . . . . . . . . . . . . 32

4.4.6 Archives . . . . . . . . . . . 32

4.4.7 Heap . . . . . . . . . . . . . 32

4.5 Score Area . . . . . . . . . . . . . . . 32

4.6 Play Area . . . . . . . . . . . . . . . . 33

4.6.6 Servers . . . . . . . . . . . . 34

4.6.7 Central Servers . . . . . . . 34

4.6.8 Remote Servers . . . . . . . 35

4.6.9 Protecting a Server . . . . . 35

4.7 Bank . . . . . . . . . . . . . . . . . . . 35

4.8 Set Aside . . . . . . . . . . . . . . . 36

4.9 Remove from the Game . . . . . . . 36
5 Turns . . . . . . . . . . . . . . . . . . . . . . 36

5.1 General . . . . . . . . . . . . . . . . . 37

5.2 Actions . . . . . . . . . . . . . . . . . 37

5.3 Draw Phase . . . . . . . . . . . . . . 38

5.4 Action Phase . . . . . . . . . . . . . 38

5.5 Discard Phase . . . . . . . . . . . . . 39

5.6 Steps of the Corp’s Turn . . . . . . 39

5.7 Steps of the Runner’s Turn . . . . . 40
6 Runs . . . . . . . . . . . . . . . . . . . . . . 40

,Failure type,Query,Baseline Top 3,Re-ranked Top 3,Retrieval time (s),Reranking time (s)
0,Added subroutines / corner case,What happens to subroutines gained during an e...,"[244, 139, 246]","[246, 138, 149]",0.018368,0.997394
1,Negation / constraint,Can a subroutine that has already been broken ...,"[246, 247, 139]","[139, 247, 245]",0.015432,0.764322
2,Exception / bypass,"When the Runner bypasses a piece of ice, what ...","[138, 149, 133]","[138, 139, 246]",0.017456,0.941293
3,Targeting already-broken subroutines,Can an ability that breaks subroutines target ...,"[247, 246, 139]","[247, 245, 246]",0.016271,0.768970
4,Fully-broken ice / exception,If a piece of ice gains new subroutines after ...,"[246, 138, 244]","[138, 244, 131]",0.021665,0.822849
5,Keyword Trap / Distractor,If the Runner breaks all subroutines on a piec...,"[138, 246, 247]","[247, 244, 138]",0.019064,0.820072
6,Exceptions & Corner Cases,If a piece of ice gains new subroutines after ...,"[138, 246, 244]","[138, 244, 246]",0.020978,0.821904
7,Negation & Constraints,Can an ability that breaks all subroutines be ...,"[246, 247, 138]","[247, 246, 139]",0.019228,1.063670
8,Other Document-Specific Failures,"If the encountered ice has no subroutines, whe...","[138, 246, 139]","[138, 139, 246]",0.019614,0.787858
9,Other Document-Specific Failure,If the Runner bypasses ice after the paid abil...,"[149, 138, 312]","[138, 149, 137]",0.018735,0.803434
10,Exceptions & Corner Cases,If multiple abilities trigger at the same time...,"[194, 272, 282]","[194, 239, 238]",0.017042,0.899517
11,Negation & Constraints,What happens if a player attempts an action th...,"[212, 45, 115]","[110, 115, 279]",0.018000,0.933224
12,Keyword Trap / Distractor,If a card effect makes another card unable to ...,"[187, 186, 170]","[187, 186, 283]",0.018537,0.841285
13,Out-of-Domain,What is the best opening strategy for winning ...,"[5, 313, 18]","[19, 18, 4]",0.015042,1.219569

### Compare LLM answers for the failure queries
Run this after the rank-analysis cell. It calls the LLM twice per query, using the identical prompt template and each pipeline's own Top 3. Inspect whether the baseline misses a rule, while the re-ranked answer correctly includes it.

In [237]:
# This cell makes 2 LLM calls per query. Set the list to only the confirmed
# failure cases if you want to reduce API usage.
failure_answer_comparisons = []

for case in failure_queries:
    time.sleep(10)
    test_query = case["query"]
    top10 = baseline_retrieve(test_query, top_k=10)
    reranked_top3 = rerank_candidates(test_query, top10, top_k=3)
    baseline_top3 = top10[:3]

    start = time.perf_counter()
    answer_baseline = generate_answer(build_prompt(test_query, baseline_top3))
    baseline_answer_time = time.perf_counter() - start

    start = time.perf_counter()
    answer_reranked = generate_answer(build_prompt(test_query, reranked_top3))
    reranked_answer_time = time.perf_counter() - start

    print("\n" + "=" * 100)
    print("FAILURE TYPE:", case["type"])
    print("QUERY:", test_query)
    print("\n--- BASELINE ANSWER ---\n")
    print(answer_baseline)
    print("\n--- RE-RANKED ANSWER ---\n")
    print(answer_reranked)
    print(f"\nLLM latency — baseline: {baseline_answer_time:.3f} s; re-ranked: {reranked_answer_time:.3f} s")

    failure_answer_comparisons.append({
        "Failure type": case["type"],
        "Query": test_query,
        "Baseline Top 3 IDs": [x["chunk_id"] for x in baseline_top3],
        "Re-ranked Top 3 IDs": [x["chunk_id"] for x in reranked_top3],
        "Baseline LLM time (s)": baseline_answer_time,
        "Re-ranked LLM time (s)": reranked_answer_time,
        "Baseline answer": answer_baseline,
        "Re-ranked answer": answer_reranked
    })

failure_answers_df = pd.DataFrame(failure_answer_comparisons)
display(failure_answers_df[[
    "Failure type", "Query", "Baseline Top 3 IDs", "Re-ranked Top 3 IDs",
    "Baseline LLM time (s)", "Re-ranked LLM time (s)"
]])

====================================================================================================
FAILURE TYPE: Added subroutines / corner case
QUERY: What happens to subroutines gained during an encounter with ice?

--- BASELINE ANSWER ---

Based on the provided context, when a piece of ice gains 1 or more new subroutines during an encounter with it, those subroutines come into existence unbroken with respect to that encounter. Additionally, if the new subroutine is of a certain category where the number increases, the new copies are added after any previously-existing subroutines in that category (or after previous subroutines, as seen in the Ashigaru example).

--- RE-RANKED ANSWER ---

Based on the provided context, when a piece of ice gains 1 or more new subroutines during an encounter with it, those subroutines come into existence unbroken with respect to that encounter.

LLM latency — baseline: 0.757 s; re-ranked: 0.641 s

====================================================================================================
FAILURE TYPE: Negation / constraint
QUERY: Can a subroutine that has already been broken be broken again?

--- BASELINE ANSWER ---

Based on the provided context, only unbroken subroutines can be chosen as targets for abilities that would break them. Furthermore, when an ability tries to break an already-broken subroutine (such as in the example with Grappling Hook), it "does nothing to the other... subroutine, because it is already broken."

Therefore, a subroutine that has already been broken cannot be broken again.

--- RE-RANKED ANSWER ---

Based on the provided context, only *unbroken* subroutines can be chosen as targets for abilities that would break them (rule 9.8.6). However, an ability like Grappling Hook can choose an *already-broken* subroutine as its target *because* it will not attempt to break the chosen subroutine (it chooses it as the one that will not be broken, or it does nothing to it because it is already broken).

Therefore, a subroutine that has already been broken cannot be broken again; when targeted by an ability like Grappling Hook, the ability "does nothing to the other... subroutine, because it is already broken."

LLM latency — baseline: 0.818 s; re-ranked: 0.972 s

====================================================================================================
FAILURE TYPE: Exception / bypass
QUERY: When the Runner bypasses a piece of ice, what happens to the encounter and its subroutines?

--- BASELINE ANSWER ---

Based on the provided context, when an effect allows the Runner to bypass a piece of ice, the Encounter Ice Phase is aborted and the Runner immediately proceeds to pass that ice.

The provided context does not contain enough information to determine what specifically happens to the encounter's subroutines when the ice is bypassed.

--- RE-RANKED ANSWER ---

Based on the provided context, when the Runner bypasses a piece of ice, the Encounter Ice Phase is aborted and the Runner immediately proceeds to pass that ice. Depending on when the bypass occurs:

* Most bypass effects occur at the beginning of an encounter, meaning subroutines are neither broken nor resolved.
* If ice is bypassed later (in step 6.9.3b), subroutines may or may not have been broken, but step 6.9.3c never occurs so no subroutines resolve.

LLM latency — baseline: 0.862 s; re-ranked: 1.938 s

====================================================================================================
FAILURE TYPE: Targeting already-broken subroutines
QUERY: Can an ability that breaks subroutines target a subroutine that is already broken?

--- BASELINE ANSWER ---

Based on the provided context, only *unbroken* subroutines can be chosen as targets for abilities that would break them (Rule 9.8.6). However, an ability like Grappling Hook that does *not* attempt to break the chosen subroutine (because it breaks "all but 1 subroutine") can choose an already-broken subroutine as its target.

--- RE-RANKED ANSWER ---

Based on the provided context, only *unbroken* subroutines can be chosen as targets for abilities that would break them (rule 9.8.6). However, an exception exists for an ability like Grappling Hook that does not attempt to break its chosen target (such as choosing a subroutine that will not be broken, or a subroutine that is already broken, as shown in the example in Chunk 247).

LLM latency — baseline: 0.704 s; re-ranked: 1.209 s

====================================================================================================
FAILURE TYPE: Fully-broken ice / exception
QUERY: If a piece of ice gains new subroutines after the Runner has fully broken it, does the Runner lose the fully-broken status, and can breaking those new subroutines fully break it again?

--- BASELINE ANSWER ---

Based on the provided context:

- The Runner **does not** lose the status of having fully broken the ice; the Runner’s status of having fully broken the ice remains in place.
- **No**, breaking those new subroutines will not fully break the ice or meet related conditions again.

--- RE-RANKED ANSWER ---

Based on the provided context, the Runner does not lose the fully-broken status if the ice gains new subroutines after they fully break it (the status remains in place). Additionally, breaking those new subroutines will not fully break the ice or meet related conditions again.

LLM latency — baseline: 1.296 s; re-ranked: 1.480 s

====================================================================================================
FAILURE TYPE: Keyword Trap / Distractor
QUERY: If the Runner breaks all subroutines on a piece of ice using abilities from different cards, does any single card count as having fully broken the ice?

--- BASELINE ANSWER ---

Based on the provided context, the answer cannot be determined from the provided context (the context does not specify whether an object can fully break the ice when abilities from *different* cards are used, other than stating that an object fully breaks the ice if all subroutines were broken using abilities on a single object).

--- RE-RANKED ANSWER ---

Based on the provided context, the answer cannot be determined from the provided context (the context does not state whether a card counts as having fully broken the ice if the subroutines are broken using abilities from *different* cards, as section 6.5.7b only addresses when all subroutines are broken using abilities on a *single* object).

LLM latency — baseline: 0.867 s; re-ranked: 1.112 s

====================================================================================================
FAILURE TYPE: Exceptions & Corner Cases
QUERY: If a piece of ice gains new subroutines after the Runner has fully broken it, does breaking those new subroutines fully break the ice again?

--- BASELINE ANSWER ---

Based on the provided context, breaking the new subroutines will not fully break the ice again.

--- RE-RANKED ANSWER ---

Based on the provided context, breaking the new subroutines will not fully break the ice again.

LLM latency — baseline: 1.704 s; re-ranked: 2.433 s

====================================================================================================
FAILURE TYPE: Negation & Constraints
QUERY: Can an ability that breaks all subroutines be used if every subroutine on the encountered ice is already broken?

--- BASELINE ANSWER ---

Based on the provided context, an ability that breaks "all subroutines" can be used as long as the encountered ice has at least 1 unbroken subroutine (Chunk 247, 9.8.6a). Therefore, it cannot be used if every subroutine on the encountered ice is already broken.

--- RE-RANKED ANSWER ---

Based on the provided context, no. An ability that breaks "all subroutines" can only be used as long as the encountered ice has at least 1 unbroken subroutine.

LLM latency — baseline: 10.785 s; re-ranked: 0.534 s

====================================================================================================
FAILURE TYPE: Other Document-Specific Failures
QUERY: If the encountered ice has no subroutines, when is the Runner considered to have fully broken it, and does any card or other object fully break it?

--- BASELINE ANSWER ---

Based on the provided context, if the encountered ice has no subroutines, the Runner fully breaks it when step 6.9.3b of the encounter begins. No objects fully break the ice in this case.

--- RE-RANKED ANSWER ---

Based on the provided context, if the encountered ice has no subroutines, the Runner fully breaks it when step 6.9.3b of the encounter begins. No objects fully break the ice in this case.

LLM latency — baseline: 0.781 s; re-ranked: 0.631 s

====================================================================================================
FAILURE TYPE: Other Document-Specific Failure
QUERY: If the Runner bypasses ice after the paid ability window has begun, do any remaining unbroken subroutines resolve?

--- BASELINE ANSWER ---

Based on the provided context, the answer cannot be determined from the provided context.

--- RE-RANKED ANSWER ---

Based on the provided context, the answer cannot be determined from the provided context.

LLM latency — baseline: 0.553 s; re-ranked: 0.542 s

====================================================================================================
FAILURE TYPE: Exceptions & Corner Cases
QUERY: If multiple abilities trigger at the same time during a turn, how is the order of resolving those abilities determined?

--- BASELINE ANSWER ---

Based on the provided context, the answer cannot be determined because the text cuts off right before explaining simultaneous effects (section 9.12.1).

--- RE-RANKED ANSWER ---

Based on the provided context, there is no information explaining how the order of resolving multiple abilities is determined if they trigger at the same time during a turn. Therefore, the answer cannot be determined from the provided context.

LLM latency — baseline: 2.267 s; re-ranked: 0.582 s

====================================================================================================
FAILURE TYPE: Negation & Constraints
QUERY: What happens if a player attempts an action that violates a restriction in the game rules, and can that action still resolve?

--- BASELINE ANSWER ---

Based on the provided context, there is no information explaining what happens if a player attempts an action that violates a restriction in the game rules, nor whether that action can still resolve. Therefore, the answer cannot be determined from the provided context.

--- RE-RANKED ANSWER ---

Based on the provided context, there is no information explaining what happens if a player attempts an action that violates a restriction in the game rules, or whether such an action can still resolve. Therefore, the answer cannot be determined from the provided context.

LLM latency — baseline: 0.781 s; re-ranked: 0.815 s

====================================================================================================
FAILURE TYPE: Keyword Trap / Distractor
QUERY: If a card effect makes another card unable to be used, does that mean the affected card is trashed, or does it remain in play?

--- BASELINE ANSWER ---

Based on the provided context, there is no mention of a card effect making another card "unable to be used." Therefore, whether the affected card is trashed or remains in play cannot be determined from the provided context.

--- RE-RANKED ANSWER ---

Based on the provided context, there is no mention of a card effect making another card "unable to be used." Therefore, the answer cannot be determined from the provided context.

LLM latency — baseline: 8.904 s; re-ranked: 8.941 s

====================================================================================================
FAILURE TYPE: Out-of-Domain
QUERY: What is the best opening strategy for winning a game of chess?

--- BASELINE ANSWER ---

The answer cannot be determined from the provided context.

--- RE-RANKED ANSWER ---

The answer cannot be determined from the provided context.

LLM latency — baseline: 4.671 s; re-ranked: 1.165 s

,Failure type,Query,Baseline Top 3 IDs,Re-ranked Top 3 IDs,Baseline LLM time (s),Re-ranked LLM time (s)
0,Added subroutines / corner case,What happens to subroutines gained during an e...,"[244, 139, 246]","[246, 138, 149]",0.757008,0.640543
1,Negation / constraint,Can a subroutine that has already been broken ...,"[246, 247, 139]","[139, 247, 245]",0.818414,0.971683
2,Exception / bypass,"When the Runner bypasses a piece of ice, what ...","[138, 149, 133]","[138, 139, 246]",0.861805,1.937850
3,Targeting already-broken subroutines,Can an ability that breaks subroutines target ...,"[247, 246, 139]","[247, 245, 246]",0.704043,1.209180
4,Fully-broken ice / exception,If a piece of ice gains new subroutines after ...,"[246, 138, 244]","[138, 244, 131]",1.296234,1.479747
5,Keyword Trap / Distractor,If the Runner breaks all subroutines on a piec...,"[138, 246, 247]","[247, 244, 138]",0.866538,1.112191
6,Exceptions & Corner Cases,If a piece of ice gains new subroutines after ...,"[138, 246, 244]","[138, 244, 246]",1.704130,2.432693
7,Negation & Constraints,Can an ability that breaks all subroutines be ...,"[246, 247, 138]","[247, 246, 139]",10.784585,0.533732
8,Other Document-Specific Failures,"If the encountered ice has no subroutines, whe...","[138, 246, 139]","[138, 139, 246]",0.780722,0.630725
9,Other Document-Specific Failure,If the Runner bypasses ice after the paid abil...,"[149, 138, 312]","[138, 149, 137]",0.553247,0.541993
10,Exceptions & Corner Cases,If multiple abilities trigger at the same time...,"[194, 272, 282]","[194, 239, 238]",2.267330,0.581806
11,Negation & Constraints,What happens if a player attempts an action th...,"[212, 45, 115]","[110, 115, 279]",0.780953,0.814512
12,Keyword Trap / Distractor,If a card effect makes another card unable to ...,"[187, 186, 170]","[187, 186, 283]",8.903513,8.941157
13,Out-of-Domain,What is the best opening strategy for winning ...,"[5, 313, 18]","[19, 18, 4]",4.670933,1.165169